<?php $_tplvar = $this->getVars();?>
<style>
<!--
td {
	padding: 9px 12px;
	color: #333;
}
.container_24 {
	margin-left: 10px;
	margin-right: auto;
}
-->
</style>
<div class="col-main">

<div id="page-content">
	
		<div class="cart-contents-table-bg-img">

			<input type="hidden" name="id_user" value="<?php echo $_tplvar['id_user']?>">
			<?php if(!empty($_tplvar['params_banking'])):?>
			<input type="hidden" name="params" value="<?php echo $_tplvar['params_banking']?>">
			<?php endif;?>
			<table cellpadding="30" style="width:100%;background-color:#fff" >
					<tr>
						<td style="padding-bottom: 5px;text-size:12px;color:green" colspan="2">
						<?php if(!empty($_tplvar['confirm'])):?>
							<h2>Il tuo ordine &eacute; andato a buon fine!</h2>
						<?php endif;?>
						</td>
					</tr>
					<tr>
						<td colspan="2">
							<a class="pngfix small-dark-button align-btn-right" href="<?php echo $_tplvar['WWW_ROOT']?>"><span class="pngfix">Home Page</span></a>
						</td>
					</tr>
			</table>

		</div>		
	
	<div class="clear"></div>
</div>
<!-- end page-content -->


</div>