<?php $_tplvar = $this->getVars();?>

<style>
<!--
.container_24 {
	margin-left: auto;
	margin-right: auto;
/* 	width: 1170px; */
}
-->
</style>			
			<div id="page-content">
				<div id="content-container" class="container_24">
				    <div id="main-content" class="grid_16 push_10">
					<div class="main-content-padding">
	
							<div>
								<h3 style="margin: 13px 0 0 ;padding-bottom: 7px;background: transparent url(<?php echo $_tplvar['WWW_ROOT']?>theme/styles/style2/images/underline-1.png) repeat-x scroll 0 100%;">
									IL MONDO GARDEN PLANET
								</h3>
							</div>
						
							<h4>
								Il mondo della natura, dei fiori, delle piante e degli animali tutto sotto lo stesso tetto.
								<br> <br>
								Il tetto di Garden Planet che da piu' di 30 anni - grazie alla disponibilitˆ, all'accoglienza e alla passione di chi ci lavora - fa vivere ai propri clienti un mondo di arte e natura, 
								sapendo consigliare, assistere e realizzare spazi eleganti ed armoniosi, sempre pronti a regalare piacevoli emozioni. 
								<br><br>
								Sotto il tetto Garden Planet potrai trovare tutto cio' di cui hai bisogno per trasformare la tua casa, il tuo ufficio, il tuo giardino in un esempio di arte e natura: piante da interno e da esterno, addobbi floreali, 
								attrezzature e decorazioni, arredo da giardino e non solo. Una ricca varietˆ di animali domestici - pesci, conigli, criceti Ð ma soprattutto un personale competente e attento in grado di seguirvi passo dopo passo 
								nella progettazione, realizzazione e manutenzione della vostra idea di arte e natura. Un'idea che diventa realtˆ grazie a Garden Planet. 
							</h4>
							<div class="clear"></div>
						</div>
					</div>
				</div>
			</div>