<?php $_tplvar = $this->getVars();?>


<div class="col-main">
	<div class="page-title">
<!-- 	<h2>Categoria Selezionata</h2> -->
	</div>

<form id="frm-forgo-st1" action="<?php echo $_tplvar['WWW_ROOT']?>?act=ForgotPassword" method="post" onsubmit="return validateFormAddBasket();">

<?php if($_tplvar['step'] == 1):?>
	
<div style="margin-bottom: 20px;">
Per recuperare la tua password inserisci la tua email utilizzata al momento della registrazione.
</div>

	<table cellspacing="0" cellpadding="20" style="width: 90%;">
		<tbody>
			<tr>
				<td class="BackGround20"></td>
				<td valign="top" align="center">
				<table cellspacing="0" cellpadding="3" style="text-align: left; width: 90%;">
					<tbody>
						<tr>
							<td style="padding-bottom: 5px; text-align:center">
								<table width="100%" cellspacing="0" cellpadding="0">
								<tbody>
									<tr>
										<td>Email</td>
										<td><input type="text" name="email" value="" style="width:100%"></td>
									</tr>
								</tbody>
								</table>
							</td>
						</tr>
						<tr>
							<td style="height: 10px;"></td>
						</tr>
						<tr>
							<td align="right">
								<button type="submit" class="button" title="Recupera la tua password" name="send" value="1" onclick="jQuery('#frm-forgo-st1').submit();"><span>Vai allo step successivo</span></button>								
							</td>
						</tr>
					</tbody>
				</table>
				</td>
				<td class="BackGround20"></td>
			</tr>
		</tbody>
	</table>


<?php elseif($_tplvar['step'] == 2):?>
<input type="hidden" name="email" value="<?php echo $_tplvar['email']?>">
<div style="margin-bottom: 20px;">
<?php if($_tplvar['error_secret_response']):?>
ATTENZIONE: La risposta inserita non è corretta!
<?php endif;?>
</div>

	<table cellspacing="0" cellpadding="10" style="width: 100%;">
		<tbody>
			<tr>
				<td class="BackGround20"></td>
				<td valign="top" align="center">
				<table cellspacing="0" cellpadding="3" style="text-align: left; width: 90%;">
					<tbody>
						<tr>
							<td style="padding-bottom: 5px; text-align:center">
								<table width="90%" cellspacing="0" cellpadding="0">
								<tbody>
									<tr>
										<td>La domanda che hai inserito in fase di registrazione è:</td>
									</tr>
									<tr>
										<td><b><?php echo $_tplvar['secret_question'];?>?</b></td>
									</tr>
									<tr>
										<td>Risposta &nbsp;<input type="text" name="secret_response" value=""></td>
									</tr>
								</tbody>
								</table>
							</td>
						</tr>
						<tr>
							<td style="height: 10px;"></td>
						</tr>
						<tr>
							<td align="right"><input type="submit" class="Button7"
								title="Recupera la tua password"
								id="CustSetUp_BtnSubmit" value="Invia Richiesta"
								name="send">
							</td>
						</tr>
					</tbody>
				</table>
				</td>
				<td class="BackGround20"></td>
			</tr>
		</tbody>
	</table>

<?php elseif($_tplvar['confirm_reset_password']):?>
<div style="margin: 40px;">
	Complimenti: La tua password è ststa reimpostata.<br>
	A breve riceverai una mail con la tua nuova password.<br><br>
	<button type="button" class="button" title="Crea un account" name="send" onclick="document.location.href='<?php echo $_tplvar['WWW_ROOT']?>?act=Login';"><span>Vai al Login</span></button>
</div>
<?php else:?>

	<table cellspacing="0" cellpadding="10" style="width: 90%;">
		<tbody>
			<tr>
				<td class="BackGround20"></td>
				<td valign="top" align="center">
				<table cellspacing="0" cellpadding="3" style="text-align: left; width: 90%;">
					<tbody>
						<tr>
							<td style="padding-bottom: 5px;">
							<table width="100%" cellspacing="0" cellpadding="0">
								<tbody>
									<tr>
										<td></td>
									</tr>
								</tbody>
							</table>
							</td>
						</tr>
						<tr>
							<td style="height: 10px;"></td>
						</tr>
						<tr>
							<td></td>
						</tr>
						<tr>
							<td style="height: 10px;"></td>
						</tr>
						<tr>
						<?php if($_tplvar['confirm_account']):?>
							<td align="right"><input type="button" class="Button7" onclick="document.location.href = '<?php echo $_tplvar['WWW_ROOT']?>/store'"></td>
						<?php else:?>
							<td align="right">
								<button type="submit" class="button" title="Crea un account" name="send" onclick="jQuery('#frm-forgo-st1').submit();"><span>Crea un account</span></button>
							</td>
						<?php endif;?>
						</tr>
					</tbody>
				</table>
				</td>
				<td class="BackGround20"></td>
			</tr>
		</tbody>
	</table>
<?php endif;?>

</form>


</div>