<?php $_tplvar = $this->getVars();?>

			<div id="home-page-content">
			
				<div id="before-content-column" class="container_24">
				
					<!-- 
					<div class="home-page-divider pngfix"></div>
					<div id="before-cont-box-1" class="column_3_of_3 home-cont-box">
						<div class="column-content-wrapper">
							<div class="cont_col_1 substitute_widget_class">
								<div class="textwidget">
									<h2 class="large-text" style="font-size:33px; margin:0 0 5px;">Stream</h2>
									<div class="featured-text"><span class="theme-color">
										E' la nuova piattaforma web di Florsistemi.<br>Grazie a Stream potrai potrai far visualizzare il tuo magazzino in tempo reale a tutti i tuoi clienti o partner commerciali.
									</div>
								</div>
							</div>
						</div>
					</div>
					 -->
					<!-- end before-cont-box-1 -->
					<div class="home-page-divider pngfix"></div>
<br><br>
					<div class="home-page-divider pngfix"></div>
					<div id="before-cont-box-1" class="column_3_of_3 home-cont-box">
						<div class="column-content-wrapper">
							<div class="cont_col_1 substitute_widget_class">
								<div class="textwidget">
									<h2 class="large-text" style="font-size:33px; margin:0 0 5px;text-align:center;">Scegli cosa vuoi vedere nei nostri listini</h2>
									<br><br>
									<div class="featured-text"><span class="theme-color">
<center>
<table style="width:90%">
<tr>
	<td align="center" style="width:145px;text-align:center">
		<a href="#"><img alt="Listino Piante" src="<?php echo $_tplvar['WWW_ROOT'].$_tplvar['IMG_DIR'];?>/icons/HomeSceltaPiante.png"></a>
	</td>
	<td align="center" style="width:145px;text-align:center">
		<img alt="Listino Piante" src="<?php echo $_tplvar['WWW_ROOT'].$_tplvar['IMG_DIR'];?>/icons/HomeSceltaPianteInterno.png"></a>
	</td>
	<td align="center" style="width:145px;text-align:center">
		<img alt="Listino Piante" src="<?php echo $_tplvar['WWW_ROOT'].$_tplvar['IMG_DIR'];?>/icons/HomeSceltaFioriRecisi.png"></a>
	</td>
	<td align="center" style="width:145px;text-align:center">
		<img alt="Listino Piante" src="<?php echo $_tplvar['WWW_ROOT'].$_tplvar['IMG_DIR'];?>/icons/HomeSceltaFioriInVaso.png"></a>
	</td>
	<td align="center" style="width:145px;text-align:center">
		<img alt="Listino Piante" src="<?php echo $_tplvar['WWW_ROOT'].$_tplvar['IMG_DIR'];?>/icons/HomeSceltaAccessori.png"></a>
	</td>
	<td align="center" style="width:145px;text-align:center">
		<img alt="Listino Piante" src="<?php echo $_tplvar['WWW_ROOT'].$_tplvar['IMG_DIR'];?>/icons/HomeSceltaArticoliGiardinaggio.png"></a>
	</td>
</tr>
<tr>
	<td align="center" style="text-align:center"><a href="#" style="color: #101010 !important;text-align:center;">Piante da Esterno</a></a></td>
	<td align="center" style="text-align:center"><a href="#" style="color: #101010 !important;text-align:center;">Piante da Interno</a></td>
	<td align="center" style="text-align:center"><a href="#" style="color: #101010 !important;text-align:center;">Fiori Recisi</a></td>
	<td align="center" style="text-align:center"><a href="#" style="color: #101010 !important;text-align:center;">Fiori in Vaso</a></td>
	<td align="center" style="text-align:center"><a href="#" style="color: #101010 !important;text-align:center;">Accessori</a></td>
	<td align="center" style="text-align:center"><a href="#" style="color: #101010 !important;text-align:center;">Articoli per il Giardinaggio</a></td>
</tr>
</table>
</center>
									</div>
								</div>
							</div>
						</div>
					</div>
					<!-- end before-cont-box-1 -->
					<div class="home-page-divider pngfix"></div>
<br><br><br>					
					
				</div>
				<!-- end before-content-column -->
				<div class="clear"></div>
			</div>
			<!-- end home-page-content -->