<?php $_tplvar = $this->getVars();
// _dump($_tplvar['content']);
foreach ($_SESSION[session_id()]['basket'] as $bsk)
	$productsInBasket[$bsk['giacenza']['id']] = $bsk;
?>
<link rel="stylesheet" id="flexslider-css" href="<?php echo $_tplvar['WWW_ROOT']?>javascript/flexslider/flexslider039c.css?ver=3.6" type="text/css" media="screen, projection" />
<script type="text/javascript" src="<?php echo $_tplvar['WWW_ROOT']?>javascript/flexslider/jquery.flexslider.min039c.js?ver=3.6"></script>

<script type="text/javascript">
	var index = 1;
	var count = 1;
	function next_image()
	{
		count = -1;
		index++;

		jQuery(".photo").each(function() {
			count++;
			if(jQuery(this).attr('index') == index)
			{
				var src = jQuery(this).attr('src').replace('small/', '');
				jQuery('#photo').attr('src', '<?php echo $_tplvar['WWW_ROOT']?>javascript/flexslider/loading.gif');
				jQuery('#photo').css('width', '20%');
				setTimeout(function(){
					jQuery('#photo').attr('src', src);
					jQuery('#photo').css('width', '90%');
				}, 1000);
			}
		});
	
		if(index >= count)
			index = 0;
	}
	function prev_image()
	{
		count = -1;
		index--;
		jQuery(".photo").each(function() {
			count++;
			if(jQuery(this).attr('index') == index)
			{
				var src = jQuery(this).attr('src').replace('small/', '');
				jQuery('#photo').attr('src', '<?php echo $_tplvar['WWW_ROOT']?>javascript/flexslider/loading.gif');
				jQuery('#photo').css('width', '20%');
				setTimeout(function(){
					jQuery('#photo').attr('src', src);
					jQuery('#photo').css('width', '90%');					
				}, 1000);
			}
		});
		if(index <= 0)
		{
			index = count;
			jQuery(".photo").each(function() {
				if(jQuery(this).attr('index') == index)
				{
					var src = jQuery(this).attr('src').replace('small/', '');
					jQuery('#photo').attr('src', '<?php echo $_tplvar['WWW_ROOT']?>javascript/flexslider/loading.gif');
					jQuery('#photo').css('width', '20%');
					setTimeout(function(){
						jQuery('#photo').attr('src', src);
						jQuery('#photo').css('width', '90%');						
					}, 1000);
				}
			});
		}
	}
	</script>

<div class="col-main">
	<div class="page-title">

<?php if(!empty($_tplvar['is_ajax'])):?>
	<link rel="stylesheet" type="text/css" href="<?php echo $_tplvar['WWW_ROOT']?>css/skin/frontend/default/megashop-green/css/styles.css" media="all" />
	<link rel="stylesheet" type="text/css" href="<?php echo $_tplvar['WWW_ROOT']?>css/skin/frontend/default/megashop-green/css/skin.css" media="all" />
	<link rel="stylesheet" type="text/css" href="<?php echo $_tplvar['WWW_ROOT']?>css/skin/frontend/default/megashop-green/css/light_box.css" media="all" />
	<link rel="stylesheet" type="text/css" href="<?php echo $_tplvar['WWW_ROOT']?>css/skin/frontend/default/megashop-green/css/widgets.css" media="all" />
	<link rel="stylesheet" type="text/css" href="<?php echo $_tplvar['WWW_ROOT']?>css/skin/frontend/default/megashop-green/css/elastislide.css" media="all" />
	<link rel="stylesheet" type="text/css" href="<?php echo $_tplvar['WWW_ROOT']?>css/skin/frontend/default/megashop-green/css/mix.css" media="all" />
	<link rel="stylesheet" type="text/css" href="<?php echo $_tplvar['WWW_ROOT']?>css/skin/frontend/default/megashop-green/css/skeleton.css" media="all" />
	<link rel="stylesheet" type="text/css" href="<?php echo $_tplvar['WWW_ROOT']?>css/skin/frontend/default/megashop-green/css/magicat.css" media="all" />
	<link rel="stylesheet" type="text/css" href="<?php echo $_tplvar['WWW_ROOT']?>css/skin/frontend/default/megashop-green/css/print.css" media="print" />
<?php endif;?>

<?php if(!empty($_REQUEST['error_friends'])):?>
<script>
jQuery(document).ready(function() {
	jQuery('#err-1-send-to-friends').show(500);
});
</script>
<div id="err-1-send-to-friends" style="position:absolute;display:none;top:10%;left:25%;padding:25px;background-color:#fff;border:1px solid #0e0ef6">
<table style="margin-top:-12px;margin-bottom:12px;margin-right: 3px;"><tr><td style="padding:18px;font-size:14px;"><?php echo $this->getTranslation('Attenzione: la mail del destinatario non &eacute; una mail valida!')?></td></tr><tr><td style="font-size:14px;"><div class="buttons-cart" style="margin-left:50px;"><a href="javascript:void(0);" onclick="jQuery('#err-1-send-to-friends').hide(500);" style="color:#fff;"><?php echo $this->getTranslation('Chiudi')?></a></strong></div></td></tr></table>
</div>			
<?php endif;?>
<?php if(!empty($_REQUEST['error_personal'])):?>
<script>
jQuery(document).ready(function() {
	jQuery('#err-2-send-to-friends').show(500);
});
</script>
<div id="err-2-send-to-friends" style="position:absolute;display:none;top:10%;left:25%;padding:25px;background-color:#fff;border:1px solid #0e0ef6">
<table style="margin-top:-12px;margin-bottom:12px;margin-right: 3px;"><tr><td style="padding:18px;font-size:14px;"><?php echo $this->getTranslation('Attenzione: la tua mail non &eacute; una mail valida!')?></td></tr><tr><td style="font-size:14px;"><div class="buttons-cart" style="margin-left:50px;"><a href="javascript:void(0);" onclick="jQuery('#err-2-send-to-friends').hide(500);" style="color:#fff;"><?php echo $this->getTranslation('Chiudi')?></a></strong></div></td></tr></table>
</div>			
<?php endif;?>
<?php if(!empty($_REQUEST['confirm'])):?>
<script>
jQuery(document).ready(function() {
	jQuery('#cnf-send-to-friends').show(500);
});
</script>
<div id="cnf-send-to-friends" style="position:absolute;display:none;top:10%;left:25%;padding:25px;background-color:#fff;border:1px solid #0e0ef6;z-index:9999;">
<table style="margin-top:-12px;margin-bottom:12px;margin-right: 3px;"><tr><td style="padding:18px;font-size:14px;"><?php echo $this->getTranslation('Email inviata correttamente!')?></td></tr><tr><td style="font-size:14px;"><div class="buttons-cart" style="margin-left:50px;"><button type="button" title="<?php echo $this->getTranslation('CHIUDI')?>" class="button btn-cart" onclick="javascript:jQuery('#cnf-send-to-friends').hide(500);"> <span><span><?php echo $this->getTranslation('CHIUDI')?></span></span></button></strong></div></td></tr></table>
</div>			
<?php endif;?>

<h2 class="ftitle" style="margin-left:20px;text-align:center;">
<?php 
	if(!empty($_tplvar['content'][0]['nome_it']))
		echo str_replace("\\", "", $_tplvar['content'][0]['nome_it']);
?>
</h2>
<?php $giacenza = $this->getGiacenzaById($_tplvar['content'][0]['id_gicenza']);?>

<script>jQuery('<img />').attr('src','<?php echo $this->getImageFromIdContent($_tplvar['content'][0]['id'], 'Large_');?>').appendTo('body').css('display','none');</script>
			
			<?php $imgs = $this->getAllImageFromIdContent($_tplvar['content'][0]['id'], 'Large_');?>
			<div style="margin-right:0px;width:100%;text-align:center;" class="flexslider">
				<ul class="flex-direction-nav">
					<?php if(count($imgs) > 1):?>
						<li><a class="prev" href="javascript:void(0);" onClick="javascipt:prev_image();">Previous</a></li>
					<?php endif;?>
					<li><img index="1" class="photo" id="photo" src="<?php echo $imgs[0]?>" title="" style="width: auto;"/></li>
					<?php if(count($imgs) > 1):?>
						<li><a class="next" href="javascript:void(0);" onClick="javascipt:next_image();">Next</a></li>
					<?php endif;?>
				</ul>					
			</div>
			<?php if(count($imgs) > 1):?>
			<div class="box-images" style="width: 100%;text-align: center;">
			<?php foreach ($imgs as $k=>$img):?>
				<img class="photo" index="<?php echo $k+1?>" src="<?php echo $img?>" title="" width="100" onClick="javascript:jQuery('#photo').attr('src', jQuery(this).attr('src').replace('small/', ''));" onMouseOver="jQuery(this).css('cursor','pointer');"/>
			<?php endforeach;?>
			</div>
			<?php endif;?>
							
				
<div class="store-item">
	<div>

		<table <?php if(empty($_tplvar['is_ajax'])):?>style="width:100%;"<?php endif;?>>
		<tr>
			<td valign="top" style="vertical-align:top;padding:20px;font-size:16px;line-height: 22px;">
			
		      <?php if(!empty($giacenza['bar_code'])):?>
		          	Codice Articolo: <b><?php echo $giacenza['bar_code']?></b><br>
			  <?php endif;?>
		      <?php if(!empty($_tplvar['content'][0]['vbn'])):?>
		          	Bar Code: <b><?php echo $_tplvar['content'][0]['vbn']?></b><br>
			  <?php endif;?>
	          
	          <?php if(!empty($_tplvar['content'][0]['nome_it'])):?>
	          	<?php echo str_replace("\\", "", $this->getTranslation('Descrizione'))?>: <b><?php echo str_replace("\\", "", $_tplvar['content'][0]['nome_it'])?></b><br>
	          <?php endif;?>
	          
	          <?php if(!empty($_tplvar['content'][0]['gruppo'])):?>
	          	<?php echo $this->getTranslation('Categoria')?>: 
				<?php
				include_once(APP_ROOT."/beans/gruppi_merceologici.php");
				$BeanCategory = new gruppi_merceologici(MyDB::connect(), $_tplvar['content'][0]['id_gm']);
				$categories_2 = $BeanCategory->dbGetCategoryTree(MyDB::connect(), null, null, $BeanCategory->parent_id);
				?>
				<?php foreach ($categories_2 as $cat):?>
				<a href="<?php echo $_tplvar['WWW_ROOT']?>?act=Search&gm=<?php echo $cat['id']?>"><b><?php echo $cat['gruppo']?></b></a> >> 
				<?php endforeach;?>
				<a href="<?php echo $_tplvar['WWW_ROOT']?>?act=Search&gm=<?php echo $_tplvar['content'][0]['id_gm']?>"><b><?php echo $_tplvar['content'][0]['gruppo']?></b></a><br>
	          <?php endif;?>

<?php if(!empty($_tplvar['content'][0]['note'])):?>
	<div style="margin-left:5px;text-align:left;">
	<?php echo str_replace("\\", "", $_tplvar['content'][0]['note']);?><br>
	</div>
<?php endif;?>
	          	<?php if(!empty($_SESSION['LoggedUser']['username'])):?>
				<div class="price-box">
					<?php if(!empty($_SESSION['LoggedUser']['sconto'][0]['percentuale'])):?>
					<span class="regular-price" id="product-price-2315"><span class="price" style="color:#BBBBBB">
						<strike><?php echo Currency::FormatEuro($giacenza['prezzo_0'])?></strike>
					</span></span>
					<?php endif;?>
					<span class="regular-price" id="product-price-2315"><span class="price">
						<?php echo Currency::FormatEuro($this->getPrezzo($giacenza));?>
					</span></span>
				</div>
				<?php endif;?>
				<input type="hidden" id="qta_min_ordine_<?php echo $_tplvar['content'][0]['id_gicenza']?>" value="<?php echo $_tplvar['content'][0]['qta_min_ordine']?>">
				<input type="hidden" id="qta_confezione_<?php echo $_tplvar['content'][0]['id_gicenza']?>" value="<?php echo $_tplvar['content'][0]['qta_minima']?>">
				<input type="hidden" id="qta_pianale_<?php echo $_tplvar['content'][0]['id_gicenza']?>" value="<?php echo $_tplvar['content'][0]['qta_pianale']?>">
				<input type="hidden" id="qta_carrello_<?php echo $_tplvar['content'][0]['id_gicenza']?>" value="<?php echo $_tplvar['content'][0]['qta_carrello']?>">
				<?php 
				$qta_selected = null;
				if($productsInBasket[$_tplvar['content'][0]['id_gicenza']]['box_type'] == 'confezione')
					$qta_selected = $productsInBasket[$_tplvar['content'][0]['id_gicenza']]['basket_qty']['sel_quantita'];
				if($productsInBasket[$_tplvar['content'][0]['id_gicenza']]['box_type'] == 'pianale')
					$qta_selected = $productsInBasket[$_tplvar['content'][0]['id_gicenza']]['basket_qty']['sel_quantita'];
				if($productsInBasket[$_tplvar['content'][0]['id_gicenza']]['box_type'] == 'carrello')
					$qta_selected = $productsInBasket[$_tplvar['content'][0]['id_gicenza']]['basket_qty']['sel_quantita'];
				?>
				<br>
				Q.ta per confezione <?php echo $_tplvar['content'][0]['qta_minima']?>
				<br>
				Q.ta per pianale <?php echo $_tplvar['content'][0]['qta_pianale']?>
				<br>
				Q.ta per carrello <?php echo $_tplvar['content'][0]['qta_carrello']?>
				<br>
				Q.ta min. ordine <?php echo $_tplvar['content'][0]['qta_min_ordine']?>	Confezioni
				<br>
				<br>
				Ordine: <input type="text" id="quantita_<?php echo $_tplvar['content'][0]['id_gicenza']?>" value="<?php echo $qta_selected?>" style="width:50px;<?php if(!empty($qta_selected)):?>background-color:#2CC951;color:#fff;<?php endif;?>">&nbsp;
				<select name="box_type_<?php echo $_tplvar['content'][0]['id_gicenza']?>" id="box_type_<?php echo $_tplvar['content'][0]['id_gicenza']?>">
					<option value="confezione" <?php if($productsInBasket[$_tplvar['content'][0]['id_gicenza']]['box_type'] == 'confezione'):?>selected="selected"<?php endif;?>>Confezione</option>
					<option value="pianale" <?php if($productsInBasket[$_tplvar['content'][0]['id_gicenza']]['box_type'] == 'pianale' || empty($productsInBasket[$_tplvar['content'][0]['id_gicenza']]['box_type'])):?>selected="selected"<?php endif;?>>Pianale</option>
					<option value="carrello" <?php if($productsInBasket[$_tplvar['content'][0]['id_gicenza']]['box_type'] == 'carrello'):?>selected="selected"<?php endif;?>>Carrello</option>
				</select>
				<br>
				<br>
				<div class="product_icons">
					<textarea style="<?php if(!empty($qta_selected)):?>background-color:#2CC951;color:#fff;<?php endif;?>font-size:10px;" cols="30" id="note_<?php echo $_tplvar['content'][0]['id_gicenza']?>" name="note_<?php echo $_tplvar['content'][0]['id_gicenza']?>" onblur="if(this.value=='') this.value='<?php echo $this->getTranslation('Inserisci una nota sul prodotto')?>'" onclick="if(this.value=='<?php echo $this->getTranslation('Inserisci una nota sul prodotto')?>') this.value=''"><?php if(empty($productsInBasket[$_tplvar['content'][0]['id_gicenza']]['note'])) echo $this->getTranslation('Inserisci una nota sul prodotto'); else echo $productsInBasket[$_tplvar['content'][0]['id_gicenza']]['note'];?></textarea>
					<button type="button" title="<?php echo $this->getTranslation('Dettaglio')?>" class="button btn-cart" onclick="javascript:addToCart('<?php echo $_tplvar['content'][0]['id_gicenza']?>');" style="margin-top:-20px;"> 
						<span><span id="btn_addcart_<?php echo $_tplvar['content'][0]['id_gicenza']?>"><?php if(!empty($qta_selected)):?><?php echo $this->getTranslation("&nbsp;&nbsp;&nbsp;Modifica")?><?php else:?><?php echo $this->getTranslation('&nbsp;Aggiungi al carrello')?><?php endif;?></span></span>
					</button>
				</div>
<br><br>
				<div class="product_icons" style="width:60%">
					<button type="button" title="<<< <?php echo $this->getTranslation('TORNA AL LISTINO')?>" class="button btn-cart" onclick="javascript:document.location.href='<?php echo $_tplvar['WWW_ROOT']?>?act=Search&gm=<?php echo $_tplvar['content'][0]['id_gm']?>';"> 
						<span><span id="btn_addcart_<?php echo $_tplvar['content'][0]['id_gicenza']?>"><<< <?php echo $this->getTranslation('TORNA AL LISTINO')?></span></span>
					</button>
					
					<button type="button" title="<?php echo $this->getTranslation('Invia a un amico')?>" class="button btn-cart" onclick="jQuery('#send-to-friends').show(500);jQuery('html, body').animate({ scrollTop: 0 }, 'slow');" 
					style="float:right;border-top: 1px #0066cc solid;border-right: 1px #0066cc solid;border-bottom: 1px #0066cc solid;border-left: 1px #0066cc solid;background: #0066cc;filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#ff0103', endColorstr='#ff0103');background: -webkit-gradient(linear, left top, left bottom, from(#0066cc), to(#0066cc));background: -moz-linear-gradient(top, #ff0103, #ff0103);text-shadow: 0px 1px #0066cc;"> 
						<span><span id="btn_addcart_<?php echo $_tplvar['content'][0]['id_gicenza']?>"><?php echo $this->getTranslation('Invia a un amico')?></span></span>
					</button>
					
				</div>
				
				
				<div id="send-to-friends" style="position:absolute;display:none;top:10%;left:25%;padding:25px;background-color:#fff;border:1px solid #0e0ef6">
				
					<form action="<?php echo $_tplvar['WWW_ROOT'];?>?act=SendToFriends" method="post" id="frm-send-to-friends">
					<?php if(!empty($giacenza['id'])):?>
						<input type="hidden" name="id_giacenza" value="<?php echo $giacenza['id']?>">
					<?php else:?>
						<input type="hidden" name="id" value="<?php echo $_tplvar['content'][0]['id_content']?>">
					<?php endif;?>
					<table style="margin-top:-12px;margin-bottom:12px;margin-right: 3px;">
					<tr>
						<td style="padding:18px;font-size:14px;">
							<table>
							<tr>
								<td colspan="2"><?php echo $this->getTranslation('Inserici la mail di un tuo amico o collega di lavoro e condividi questo prodotto')?></td>
							</tr>
							<tr>
								<td><?php echo $this->getTranslation('La tua Mail')?><?php echo $this->getTranslation(' o il tuo Nome e Cognome')?>:</td>
								<td><input type="text" name="personal_email"></td>
							</tr>
							<tr>
								<td><?php echo $this->getTranslation('La Mail del destinatario')?>:</td>
								<td><input type="text" name="frined_email"></td>
							</tr>
							<tr>
								<td><?php echo $this->getTranslation('Testo Mail')?>:</td>
								<td><textarea name ="text_mail" style="width:138px; margin-top:10px; height:45px"></textarea></td>
							</tr>
							</table>
						</td>
					</tr>
					<tr>
						<td style="padding-left: 18px;font-size:14px;">
							<button type="button" title="<?php echo $this->getTranslation('INVIA')?>" class="button btn-cart" onclick="javascript:jQuery('#frm-send-to-friends').submit();"> 
								<span><span><?php echo $this->getTranslation('INVIA')?></span></span>
							</button>
							<button type="button" title="<?php echo $this->getTranslation('CHIUDI')?>" class="button btn-cart" onclick="javascript:jQuery('#send-to-friends').hide(500);"> 
								<span><span><?php echo $this->getTranslation('CHIUDI')?></span></span>
							</button>
							
						</td>
					</tr>
					</table>
					</form>
				</div>				
				
			</td>
		</tr>
		</table>
	</div>
	
<?php //if(empty($_tplvar['is_ajax'])):?>
	<!-- <iframe src="https://www.facebook.com/plugins/like.php?href=<?php echo $_tplvar['WWW_ROOT']?>Detail/<?php echo $_tplvar['content'][0]['name'];?>/<?php echo str_replace(' ','%20',str_replace("'","", str_replace('"','', $_tplvar['content'][0]['name_it'])))?>/<?php echo $_tplvar['content'][0]['id']?>.html" scrolling="no" frameborder="0" style="border:none; width:450px; height:80px;margin-left:20px"></iframe> -->
<?php //endif;?>
</div>
<br>


<?php //if(empty($_tplvar['is_ajax'])):?>
<script type="text/javascript">
<!--
function validateForm()
{
	var email = $('#email').val();
	var richiesta = $('#richiesta').val();
	var captcha_code = $('#captcha_code').val();
	var ret = true;
	
	if(email == '')
	{
		$('#email').css('border', '1px solid red');
		ret = false;
	}
	else
		$('#email').css('border', '#555555');
	if(richiesta == '')
	{
		$('#richiesta').css('border', '1px solid red');
		ret = false;
	}
	else
		$('#richiesta').css('border', '#555555');
//	if(captcha_code == '')
//	{
//		$('#captcha_code').css('border', '1px solid red');
//		ret = false;
//	}
//	else
//		$('#captcha_code').css('border', '#555555');

	return ret;
}
//-->
</script>

<form action="<?php echo $_tplvar['WWW_ROOT']?>?act=RequestInfo" method="post" onsubmit="javascript:return validateForm();">
<table style="width: 100%;margin-left:20px;font-size:14px;display:none;">
	<tbody>
	<tr>
		<th colspan="2" align="center">Richiedi ulteriori informazioni su questo articolo</th>
	</tr>
	<tr>
		<th colspan="2">&nbsp;</th>
	</tr>
	<tr>
		<th align="right" width="250">Nome&nbsp;</th>
		<th align="left" style="padding:6px;"><input type="text" name="nome" value="<?php echo $_tplvar['customer_data']['nome']?>" style="width:200px"></th>
	</tr>
	<tr>
		<th align="right">Cognome&nbsp;</th>
		<th align="left" style="padding:6px;"><input type="text" name="cognome" value="<?php echo $_tplvar['customer_data']['cognome']?>" style="width:200px"></th>
	</tr>
	<tr>
		<th align="right">Telefono&nbsp;</th>
		<th align="left" style="padding:6px;"><input type="text" name="telefono" value="<?php echo $_tplvar['customer_data']['telefono']?>" style="width:200px"></th>
	</tr>
	<tr>
		<th align="right">Indirizzo email *&nbsp;</th>
		<th align="left" style="padding:6px;"><input type="text" id="email" name="email" value="<?php echo $_tplvar['customer_data']['email']?>" style="width:200px"></th>
	</tr>
	<tr>
		<th align="right">Localit&agrave; (Regione,Provincia o Citt&agrave;)&nbsp;</th>
		<th align="left" style="padding:6px;"><input type="text" name="localita" value="<?php echo $_tplvar['customer_data']['localita']?>" style="width:200px"></th>
	</tr>
	<tr>
		<th align="right" valign="top">Richiesta *&nbsp;</th>
		<th align="left" style="padding:6px;"><textarea rows="4" cols="26" id="richiesta" name="richiesta"><?php echo $_tplvar['customer_data']['richiesta']?></textarea></th>
	</tr>
	<tr>
		<th>&nbsp;</th>
		<th align="left" style="padding:6px;">
			<script type="text/javascript">
			var RecaptchaOptions = {
				theme : 'blackglass'
			};
			</script>		
			<script type="text/javascript" src="http://www.google.com/recaptcha/api/challenge?k=<?php echo GOOGLE_RECAPCHA_PUBLIC_KEY;?>"></script>
			<noscript>
			<iframe src="http://www.google.com/recaptcha/api/noscript?k=<?php echo GOOGLE_RECAPCHA_PUBLIC_KEY;?>" height="300" width="500" frameborder="0"></iframe><br>
			<textarea name="recaptcha_challenge_field" rows="3" cols="40"></textarea>
			<input type="hidden" name="recaptcha_response_field" value="manual_challenge">
			</noscript>
		</th>
	</tr>
	<?php if($_tplvar['error_captcha']):?>
	<tr>
		<th colspan="2" style="color:red;padding:6px;">Attenzione errore nell'inserimento del Captcha</th>
	</tr>
	<?php endif;?>
	<tr>
		<th>(*) Campi obbligatori</th>
		<th style="padding:6px;"><input type="submit" value="Invia Richiesta"></th>
	</tr>
	<?php if($_tplvar['confirm']):?>
	<tr>
		<th colspan="2" style="color:green;padding:6px;">La tua richiesta &egrave; stata inviata correttamente</th>
	</tr>
	<?php endif;?>
	</tbody>
</table>
</form>

<div class="clear"></div>

<style>
.crop{
    float:left;
    margin:.5em 10px .5em 0;
    overflow:hidden;
    position:relative;
    border:0px solid #ccc;
    width:180px;
    height:85px;
    }
.crop img{
    position:absolute;
    top:0px;
    left:0px;
    }
</style>

<br>
<br>
<?php if(!empty($_tplvar['releated'])):?>
<h2 class="ftitle">Ti consigliamo anche</h2>
<?php endif;?>
							<?php 
							$rowForBox = 8;
							?>
							<div class="store-cont">
							<?php foreach($_tplvar['releated'] as $key => $product):?>
								<?php $index++;?>
								<?php if(!empty($product) && $index <= $rowForBox):?>
								<?php $hrefCategory = $product['name']?>
									<div class="item-box" style="min-height: 220px;">
										<?php $image = $this->getImageFromIdContent($product['id'], 'Large_', '100')?>
										<?php if(!empty($image)):?>
										<a href="<?php echo $_tplvar['WWW_ROOT']?>Detail/<?php echo $hrefCategory;?>/<?php echo str_replace(' ','-',str_replace("'","", str_replace('"','', $product['name_it'])))?>/<?php echo $product['id']?>.html">
											<?php echo $image;?>
										</a>
										<?php else:?>
											<img alt="" src="<?php echo $_tplvar['WWW_ROOT'].$_tplvar['IMG_DIR']?>/logo_fattura.png" width="100" height="95">
										<?php endif;?>
										</p>
										<div class="item_name">
											<a href="<?php echo $_tplvar['WWW_ROOT']?>Detail/<?php echo $hrefCategory;?>/<?php echo str_replace(' ','-',str_replace("'","", str_replace('"','', $product['name_it'])))?>/<?php echo $product['id']?>.html">
												<?php echo $product['name_band'];?><br>
												<?php echo substr($product['name_it'], 0, $_tplvar['SHOP_TRUNCATE_TEXT']);?>
											</a>
										</div>
										<?php 
										$qty = 0;
										$qty_color = null;
										$qty_size = null;
										foreach ($product['magazzino'] as $giacenze)
										{
											$qty += $giacenze['quantita'];
											if(!empty($giacenze['color']))
												$qty_color[ucfirst(strtolower($giacenze['color']))] += $giacenze['quantita'];
											if(!empty($giacenze['size']))
												$qty_size[ucfirst(strtolower($giacenze['size']))] += $giacenze['quantita'];
										}
										?>										
										<div class="disp">
										<?php if($product['magazzino'][0]['quantita'] > 0):?>
											Disponibile
										<?php elseif($product['magazzino'][0]['is_in_ecommerce']):?>
											Acquistabile in negozio
										<?php else:?>
											<p style="color:#F9D616">Non Disponibile</p>
										<?php endif;?>
										</div>
										<div class="price">
											<a href="javascript:void(0);" onclick="javascript:
												$('#detail_qty_<?php echo $product['id']?>').show();">
												Taglie e colori&nbsp;(<?php echo $qty?>)
											</a>
											<a id="lnk_<?php echo $product['id']?>" href="javascript:void(0);" onclick="javascript:
												$.ajax({
													  url: '<?php echo $_tplvar['WWW_ROOT']?>?act=AjaxSetListCompare',
													  type: 'POST',
													  dataType: 'html',
													  data: 'id_content=<?php echo $product['id']?>',
													  success: function(html){
														  $('#lnk_<?php echo $product['id']?>').css('color', 'green');
														  $('#prodicts_compared').html(html);
														  //$('#res_<?php echo $product['id']?>').show();
													  }
													});">
												Confronta Prodotto
											</a>
										</div>
										
<!--										<div id="res_<?php echo $product['id']?>"></div>-->
										
										<div id="detail_qty_<?php echo $product['id']?>" style="width:auto;display:none;position:absolute;background-color:#1A1A1A;z-index:1;border:1px solid #fff;">
										<dir id="sidebar">										
											<div id="nav_menu-3" class="widget_nav_menu widget" style="background:transparent url(../images/border_dot_light.png) repeat-x left top">
												<div class="winner">
												<h4 class="wtitle">TAGLIE E COLORI</h4><br>
													<div class="menu-abbigliamento-container">
													<ul id="menu-abbigliamento" class="menu">
														<?php 														
														if(is_array($qty_color)): 
														?>
														<li id="menu-item-115" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-115">
															Colori disponibili
														</li>
														<?php
															foreach ($qty_color as $key => $val):
														?>
														<li id="menu-item-115" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-115">
															<?php echo $key?>&nbsp;(<?php echo $val?>)
														</li>
														<?php 
															endforeach;
														endif;
														?>
													</ul>
													<ul id="menu-abbigliamento" class="menu">
														<?php 														
														if(is_array($qty_size)): 
														?>
														<li id="menu-item-115" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-115">
															Taglie disponibili
														</li>
														<?php foreach ($qty_size as $key => $val):?>
														<li id="menu-item-115" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-115">
															<?php echo $key?>&nbsp;(<?php echo $val?>)
														</li>
														<?php 
															endforeach;
														endif;
														?>
													</ul>
													<ul id="menu-abbigliamento" class="menu">
														<li id="menu-item-115" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-115">
															<a href="javascript:void(0);" onclick="javascript:$('#detail_qty_<?php echo $product['id']?>').hide();">Chiudi</a>
														</li>
													</ul>
													</div>
												</div>
											</div>
										</dir>
										</div>

										<div class="price">
										<?php if(!empty($product['price_discounted_it'])):?>
											<b>&euro;&nbsp;</b><?php echo $this->getFormatPrice($product['price_discounted_it'])?>
										<?php else:?>
											<b>&euro;&nbsp;</b><?php echo $this->getFormatPrice($product['price_it'])?>
										<?php endif;?>
										</div>
									</div>
								<?php else:?>
<!--									<div class="store-cont"><div class="item-box">&nbsp;</div></div>-->
								<?php endif;?>
								
								<?php endforeach;?>
								
								<div class="clear"></div>
							</div>
<?php //endif;?>
							<div class="clear"></div>
	</div>
