<?php $_tplvar = $this->getVars();?>
<div class="postwrap fix">
<div class="post-900 page type-page status-publish hentry" id="post-900">
<div class="copy fix">
<div class="textcontent">
<div id="tab_reg">

<form action="<?php echo $_tplvar['WWW_ROOT']?>?act=ForgotPassword" method="post" onsubmit="return validateFormAddBasket();">

<?php if($_tplvar['step'] == 1):?>
	
<div style="margin-bottom: 20px;">
Per recuperare la tua password inserisci la tua email utilizzata al momento della registrazione.
</div>

	<table cellspacing="0" cellpadding="10" style="width: 100%;">
		<tbody>
			<tr>
				<td class="BackGround20"></td>
				<td valign="top" align="center">
				<table cellspacing="0" cellpadding="3" style="text-align: left; width: 100%;">
					<tbody>
						<tr>
							<td style="padding-bottom: 5px; text-align:center">
								<table width="100%" cellspacing="0" cellpadding="0">
								<tbody>
									<tr>
										<td>Email</td>
										<td><input type="text" name="email" value=""></td>
									</tr>
								</tbody>
								</table>
							</td>
						</tr>
						<tr>
							<td style="height: 10px;"></td>
						</tr>
						<tr>
							<td align="right"><input type="submit" class="Button7"
								title="Recupera la tua password"
								id="CustSetUp_BtnSubmit" value="Vai allo step successivo"
								name="CustSetUp$BtnSubmit">
							</td>
						</tr>
					</tbody>
				</table>
				</td>
				<td class="BackGround20"></td>
			</tr>
		</tbody>
	</table>


<?php elseif($_tplvar['step'] == 2):?>
<input type="hidden" name="email" value="<?php echo $_tplvar['email']?>">
<div style="margin-bottom: 20px;">
<?php if($_tplvar['error_secret_response']):?>
ATTENZIONE: La risposta inserita non è corretta!
<?php endif;?>
</div>

	<table cellspacing="0" cellpadding="10" style="width: 100%;">
		<tbody>
			<tr>
				<td class="BackGround20"></td>
				<td valign="top" align="center">
				<table cellspacing="0" cellpadding="3" style="text-align: left; width: 100%;">
					<tbody>
						<tr>
							<td style="padding-bottom: 5px; text-align:center">
								<table width="100%" cellspacing="0" cellpadding="0">
								<tbody>
									<tr>
										<td>La domanda che hai inserito in fase di registrazione è:</td>
									</tr>
									<tr>
										<td><b><?php echo $_tplvar['secret_question'];?>?</b></td>
									</tr>
									<tr>
										<td>Risposta &nbsp;<input type="text" name="secret_response" value=""></td>
									</tr>
								</tbody>
								</table>
							</td>
						</tr>
						<tr>
							<td style="height: 10px;"></td>
						</tr>
						<tr>
							<td align="right"><input type="submit" class="Button7"
								title="Recupera la tua password"
								id="CustSetUp_BtnSubmit" value="Invia Richiesta"
								name="send">
							</td>
						</tr>
					</tbody>
				</table>
				</td>
				<td class="BackGround20"></td>
			</tr>
		</tbody>
	</table>

<?php elseif($_tplvar['confirm_reset_password']):?>
<div style="margin-bottom: 20px;">
	Complimenti: La tua password è ststa reimpostata.<br>
	A breve riceverai una mail con la tua nuova password.
</div>
<?php else:?>

	<table cellspacing="0" cellpadding="10" style="width: 100%;">
		<tbody>
			<tr>
				<td class="BackGround20"></td>
				<td valign="top" align="center">
				<table cellspacing="0" cellpadding="3"
					style="text-align: left; width: 100%;">
					<tbody>
						<tr>
							<td style="padding-bottom: 5px;">
							<table width="100%" cellspacing="0" cellpadding="0">
								<tbody>
									<tr>
										<td></td>
									</tr>
								</tbody>
							</table>
							</td>
						</tr>
						<tr>
							<td style="height: 10px;"></td>
						</tr>
						<tr>
							<td></td>
						</tr>
						<tr>
							<td style="height: 10px;"></td>
						</tr>
						<tr>
						<?php if($_tplvar['confirm_account']):?>
							<td align="right"><input type="button" class="Button7" onclick="document.location.href = '<?php echo $_tplvar['WWW_ROOT']?>/store'"></td>
						<?php else:?>
							<td align="right"><input type="submit" class="Button7"
								title="Clicca qui per creare il tuo account"
								id="CustSetUp_BtnSubmit" value="Crea un account"
								name="CustSetUp$BtnSubmit"></td>
						<?php endif;?>
						</tr>
					</tbody>
				</table>
				</td>
				<td class="BackGround20"></td>
			</tr>
		</tbody>
	</table>
<?php endif;?>

</form>
</div>
<div class="clear"></div>

<div class="clear"></div>
</div>
<div class="tags">&nbsp;</div>
</div>


</div>
<!--post --></div>
