<?php $_tplvar = $this->getVars();?>


<?php if(!empty($_REQUEST['detail'])):?>
<?php foreach ($_tplvar['list'] as $key => $ordini):?>
<?php if($ordini['id'] == $_REQUEST['id_ordine']):?>

<div class=detail-ordini>
	<?php if(!empty($ordini['ordini_gardesana'])):?>
		<table cellspacing="10" cellpadding="14" style="width: 100%; background-color:#fff">
			<tr>
				<td nowrap=nowrap align=center>Ordine N.</td>
				<td nowrap=nowrap align=center>Modalit&aacute; di Pagamento</td>
				<td nowrap=nowrap align=center>Stato</td>
				<td nowrap=nowrap align=center>Traking</td>
			</tr>
			<tr>
				<td nowrap=nowrap align=center><?php echo $ordini['id']?></td>
				<td nowrap=nowrap align=center><?php echo $ordini['tipo_pagamento']?>
				</td>
				<td nowrap=nowrap align=center><?php if($ordini['spedito']):?>Spedito
					con <?php echo $ordini['corriere']?> <?php else:?>In Lavorazione<?php endif;?>
				</td>
				<td nowrap=nowrap align=center><?php echo $ordini['traking']?></td>
			</tr>
			<tr>
				<td nowrap=nowrap align=center>Variet&aacute;</td>
				<td nowrap=nowrap align=center>Prezzo</td>
				<td nowrap=nowrap align=center>Quantit&aacute;</td>
				<td nowrap=nowrap align=center>Importo</td>
			</tr>
			<?php foreach ($ordini['ordini_gardesana']['ordini_magazzino'] as $ordine):?>
			<tr>
				<td nowrap=nowrap align=center><?php echo $ordine['content']['nome_it']?>
				</td>
				<td nowrap=nowrap align=center><?php echo Currency::FormatEuro($ordine['content'][$_tplvar['key_prezzo']])?>
				</td>
				<td nowrap=nowrap align=center><?php echo $ordine['ordine_magazzino']['quantita']?>
				</td>
				<td nowrap=nowrap align=center><?php echo Currency::FormatEuro($ordine['ordine_magazzino']['importo'])?>
				</td>
			</tr>
			<?php endforeach;?>
			<tr>
				<td></td>
				<td></td>
				<td>Importo</td>
				<td><?php echo Currency::FormatEuro($ordini['importo']);?></td>
			</tr>
		</table>
		<br>
	<?php endif;?>
	<?php if(!empty($ordini['ordini_den_dekker'])):?>
		<table cellspacing="10" cellpadding="14" style="width: 100%; background-color:#fff">
			<tr>
				<td nowrap=nowrap align=center>Ordine n.</td>
				<td nowrap=nowrap align=center>Modalit&aacute; di Pagamento</td>
				<td nowrap=nowrap align=center>Stato</td>
			</tr>
			<tr>
				<td nowrap=nowrap align=center><?php echo $ordini['id']?></td>
				<td nowrap=nowrap align=center><?php echo $ordini['tipo_pagamento']?>
				</td>
				<td nowrap=nowrap align=center><?php if($ordini['spedito']):?>Spedito<?php else:?>In
					Lavorazione<?php endif;?></td>
			</tr>
			<tr>
				<td nowrap=nowrap align=center colspan=3>Prodotti Acquistati</td>
				</td>
			
			
			<tr>
				<td nowrap=nowrap align=center colspan=3><table width=100%>
						<?php foreach($ordini['ordini_den_dekker']['ordini_magazzino'] as $key => $val):?>
						<?php if($key == 0):?>
						<tr>
							<td nowrap=nowrap align=center>Descrizione</td>
							<td nowrap=nowrap align=center><?php if(!empty($val['ordine_magazzino']['quantita_pianale'])):?>Quantita
								Pianali<?php else:?>Quantita Imaballi<?php endif;?>
							</td>
							<td nowrap=nowrap align=center>Importo</td>
							<td nowrap=nowrap align=center>Nota</td>
							<td nowrap=nowrap align=center>Indispensabile x Spedizione</td>
						</tr>
						<?php endif;?>
						<tr>
							<td nowrap=nowrap align=center><?php echo $val['magazzino']['descrizione']?>
							</td>
							<td nowrap=nowrap align=center><?php if(!empty($val['ordine_magazzino']['quantita_pianale'])):?>
								<?php echo $val['ordine_magazzino']['quantita_pianale']?> <?php else:?>
								<?php echo $val['ordine_magazzino']['quantita']?> <?php endif;?>
							</td>
							<td nowrap=nowrap align=center><?php echo $val['ordine_magazzino']['importo']?>
							</td>
							<td nowrap=nowrap align=center><?php echo $val['ordine_magazzino']['nota']?>
							</td>
							<td nowrap=nowrap align=center><?php if(!empty($val['ordine_magazzino']['indispensabile'])):?>Si<?php else:?>No<?php endif;?>
							</td>
						</tr>
						<?php endforeach;?>
					</table></td>
			</tr>
		</table>
	<?php endif;?>
</div>


<?php endif;?>
<?php endforeach;?>

<?php else:?>

<style>
.container_24 {
	margin-left: auto;
	margin-right: auto;
}
.detail-orders td {
	padding: 9px 12px;
	color: #333;
}
td{
padding:10px;
}
</style>
			<div id="page-content">
				<div id="page-content-header" class="container_24">
					<div id="page-title">
						<h2>Lista Ordini</h2>
					</div>
<!--					<p class="breadcrumbs"><span class="breadcrumb_info">Ti trovi in:</span> <a href="index.php">Home</a><span class="breadarrow"> &raquo; </span><span class="current_crumb">Lista Ordini</span></p>-->
				</div>
				<div id="content-container" class="container_24">
					<div id="main-content" class="grid_17">
						<div class="main-content-padding">
							<div class="page">
								<div class="entry">
									<div class="cart-contents-table-bg-img">
									
									<table cellspacing="10" cellpadding="14" style="width: 100%; background-color:#fff">
									<tbody>
										<tr align="left"">
											<th scope="col" width="100" style="text-align:center;">&nbsp;</th>
										</tr>
										<tr align="left"">
											<th scope="col" width="65" style="text-align:center;">Id Ordine</th>
											<th scope="col" width="150" style="text-align:center;">Data</th>
											<th scope="col" width="100" style="text-align:center;">Stato</th>
											<th scope="col" style="text-align:center;">Totale dell'ordine</th>
											<th scope="col" style="text-align:center;">Dettaglio Ordine</th>
										</tr>
		
										<?php foreach ($_tplvar['list'] as $key => $ordini):?>
										<tr valign="top" align="left">
											<td style="text-align:center;">
												N. <?php echo $ordini['id']?>
											</td>									
											<td style="text-align:center;">
												<?php 
													$exp = explode(' ', $ordini['data_inserimento_riga']);
													echo $this->getFormatDate($exp[0]).' '.$exp[1];
												?>
											</td>
											<td style="text-align:center;" nowrap="nowrap"><span><?php if($ordini['spedito']):?>Spedito<?php else:?>In lavorazione<?php endif;?></span>&nbsp;</td>
											<td style="text-align:center;">
												<?php echo Currency::FormatEuro($ordini['importo'])?>
											</td>
											<td style="text-align:center;">

												<a href="<?php echo $_tplvar['WWW_ROOT'].'?act=Orders&user_id='.$_REQUEST['user_id']?>&detail=1&id_ordine=<?php echo $ordini['id']?>">										
													Dettaglio ordine
												</a>
											
											</td>
										</tr>
										<?php endforeach;?>
										<tr>
											<td colspan="5">
												<!-- Page Navigation -->
												<?php
												$assign['keys_search'] = '&user_id='.$_REQUEST['user_id']; 
												echo $this->getPartial('shared/Paging', $assign);
												?>
												<!-- /Page Navigation -->
											</td>
										</tr>
									</tbody>
								</table>
				
				
						</div>
					</div>
				</div>
				<div class="clear"></div>
			</div>
			<!-- end main-content-padding -->
		</div>
		<!-- end main-content -->
		<!-- start categories -->
		<?php //echo $this->getPartial('shared/BoxUserData');?>
		<!-- end categories -->
	</div>
	<!-- end content-container -->
	<div class="clear"></div>
</div>
<!-- end page-content -->
<?php endif;?>
