<?php $_tplvar = $this->getVars();?>


<?php if(!empty($_tplvar['user_data'])):?>
	<table style="width:900px;">
	<tr>
		<td colspan="10" valign="top" align="center" style="font-size:22px">Dettaglio Cliente</td>
	</tr>
	<tr>
		<td>Nome</td>
		<td>Cognome</td>
		<td>Email</td>
		<td>Indirizzo</td>
		<td>Citt&aacute;</td>
		<td>Provincia</td>
		<td>Cap</td>
		<td>Telefono</td>
		<td>Cellulare</td>
		<td>Sesso</td>
	</tr>
	<tr>
		<td><?php echo $_tplvar['user_data']['name']?></td>
		<td><?php echo $_tplvar['user_data']['surname']?></td>
		<td><?php echo $_tplvar['user_data']['email']?></td>
		<td><?php echo $_tplvar['user_data']['address']?></td>
		<td><?php echo $_tplvar['user_data']['city']?></td>
		<td><?php echo $_tplvar['user_data']['province']?></td>
		<td><?php echo $_tplvar['user_data']['cap']?></td>
		<td><?php echo $_tplvar['user_data']['phone']?></td>
		<td><?php echo $_tplvar['user_data']['mobile']?></td>
		<td><?php echo $_tplvar['user_data']['sex']?></td>
	</tr>
	</table>
			
<?php endif;?>
<?php if(!empty($_tplvar['data'])):?>
	<table style="width:590px;vertical-align: top;border-spacing: 15px;border: 1px solid black;">
	<tr>
		<td colspan="8" valign="top" align="center" style="font-size:22px">Dettaglio Prodotti Acquistati</td>
	</tr>
	<tr> 
		<td><h4>VARIET&Agrave;</h4></td>
		<td><h4>QUANTIT&Agrave;</h4></td>
		<td><h4>PREZZO</h4></td>
		<td><h4>IMPORTO PAGATO</h4></td>
	</tr>
	<?php foreach($_tplvar['data'] as $key => $value):?>
	<tr>
		<td><?php echo $value['content']['nome_it']?></td>
		<?php if ($value['box_type'] == 'pianale'):?>
		<?php $quantita = $value['quantita']*$value['giacenze']['qta_pianale']?>
		<?php elseif ($value['box_type'] == 'carrello'):?>
		<?php $quantita = $value['quantita']*$value['giacenze']['qta_carrello']?>
		<?php elseif ($value['box_type'] == 'confezione'):?>
		<?php $quantita = $value['quantita']*$value['giacenze']['qta_minima']?>
		<?php endif;?>
		<td><?php echo $quantita?></td>
		<td><?php echo Currency::FormatEuro(round(str_replace(',', '.', $value['importo'])/$quantita, 2, PHP_ROUND_HALF_UP))?></td>
		<td><?php echo round(str_replace(',', '.', $value['importo']), 2, PHP_ROUND_HALF_UP)?></td>
	</tr>
	<?php endforeach;?>
	<tr>
		<td><b>Totale + Iva + Sped</b></td>
		<td></td>
		<td></td>
		<td><b><?php echo round(str_replace(',', '.', $_tplvar['data'][0]['importo_ivato']), 2, PHP_ROUND_HALF_UP)?></b></td>
	</tr>	
</table>
<?php endif;?>

