						<div class="block block-list block-compare">
							<div class="block-title">
								
								<strong><span>Prodotti a Confronto</span></strong>
							</div>
						    <div class="block-content">
						    	<p class="empty">Non ci sono prodotti da confrontare.</p>
							</div>
						</div>
						<!-- Banner 1 -->
						<div class="block block-banner">
							<div class="block-content">
								<a href="#" title="Easy Returns"><img src="<?php echo $_tplvar['WWW_ROOT']?>/css/images/sidebar_banner.jpg" alt="" /></a>
							</div>
						</div>
						<!-- Banner 1 -->
						<!-- Banner 2 -->
						<div class="block block-banner">
							<div class="block-content">
								<a href="#" title="We Here to Help"><img src="<?php echo $_tplvar['WWW_ROOT']?>/css/images/sidebar_banner_2.jpg" alt="" /></a>
							</div>
						</div>
						<!-- Banner 2 -->
					
						<div class="block block-subscribe">
							<div class="block-title">
								<strong><span>Newsletter</span></strong>
							</div>
						    <form action="" method="post" id="newsletter-validate-detail">
								<div class="block-content">
									<label for="newsletter">Sottoscrivi le nostre Newsletter:</label>
									<div class="input-box">
										<input type="text" name="email" id="newsletter" title="Sottoscrivi le nostre Newsletter" class="input-text required-entry validate-email" />
									</div>
									<div class="actions">
										<button type="submit" title="Subscribe" class="button"><span><span>Sottoscrivi</span></span></button>
									</div>
								</div>
							</form>
						    <script type="text/javascript">
						    //<![CDATA[
						        var newsletterSubscriberFormDetail = new VarienForm('newsletter-validate-detail');
						    //]]>
						    </script>
						</div>
						<div class="paypal-logo">
						    <a href="#" title="" onclick="javascript:window.open('https://www.paypal.com/us/cgi-bin/webscr?cmd=xpt/Marketing/popup/OLCWhatIsPayPal-outside','paypal','width=600,height=350,left=0,top=0,location=no,status=yes,scrollbars=yes,resizable=yes'); return false;">
						    	<img src="<?php echo $_tplvar['WWW_ROOT']?>/css/images/bnr_nowAccepting_150x60.gif" alt="PayPal" title="PayPal" />
						    </a>
						</div>
					</div>