<?php $_tplvar = $this->getVars();?>
	<script type="text/javascript" src="<?php echo $_tplvar['WWW_ROOT'].$_tplvar['JS_DIR'];?>/jquery.fancybox/jquery-1.4.3.min.js"></script>
	<script>
		!window.jQuery && document.write('<script src="<?php echo $_tplvar['WWW_ROOT'].$_tplvar['JS_DIR'];?>/jquery.fancybox/jquery-1.4.3.min.js"><\/script>');
	</script>
	<script type="text/javascript" src="<?php echo $_tplvar['WWW_ROOT'].$_tplvar['JS_DIR'];?>/jquery.fancybox/fancybox/jquery.mousewheel-3.0.4.pack.js"></script>
	<script type="text/javascript" src="<?php echo $_tplvar['WWW_ROOT'].$_tplvar['JS_DIR'];?>/jquery.fancybox/fancybox/jquery.fancybox-1.3.4.pack.js"></script>
	<link rel="stylesheet" type="text/css" href="<?php echo $_tplvar['WWW_ROOT'].$_tplvar['JS_DIR'];?>/jquery.fancybox/fancybox/jquery.fancybox-1.3.4.css" media="screen" />

<?php if(empty($_REQUEST['act']) || $_REQUEST['act'] == 'Home'):?>
	<?php if($_tplvar['LoggedUser'] && empty($_SESSION['view_disclaim_newsletter'])):?>
		<?php if(!$_tplvar['LoggedUser']['is_newsletter_subscribed']):?>
			<a id="hidden_link" href="#html_newsletter_homepage"></a>
			<script type="text/javascript">
			 $(document).ready(function() {
			        $("#hidden_link").fancybox({
						'titlePosition'		: 'inside',
						'transitionIn'		: 'none',
						'transitionOut'		: 'none'
					}).trigger('click');
			    });
			</script>
			<?php $_SESSION['view_disclaim_newsletter'] = true;?>
		<?php endif;?>
	<?php elseif(empty($_SESSION['view_disclaim_newsletter'])):?>
		<a id="hidden_link" href="#html_newsletter_homepage"></a>
		<script type="text/javascript">
		 $(document).ready(function() {
		        $("#hidden_link").fancybox({
					'titlePosition'		: 'inside',
					'transitionIn'		: 'none',
					'transitionOut'		: 'none'
				}).trigger('click');
		    });
		</script>
		<?php $_SESSION['view_disclaim_newsletter'] = true;?>
	<?php endif;?>
 <?php endif;?>
<div style="display: none;">
 <div id="html_newsletter_homepage" style="width:300px;background: url('<?php echo $_tplvar['wp_external_root']?>/wp-content/themes/stationpro/images/hl-dot-black.gif') repeat-x scroll left top #1A1A1A;">
	<form action="<?php echo $_tplvar['WWW_ROOT']?>?act=NewsletterSubscribe" method="post">
		<table width="100%" style="padding:10px">
		<tr>
			<td align="center">
				Iscriviti subito alla nostra Newsletter<br>per te in anteprima novità e promozioni !!!<br>
				inserisci qui la tua EMAIL: <br>
			</td>
		</tr>
		<tr>
			<td align="center" style="padding:10px">
				<input type="text" name="newsletter_email" value="" style="background: none repeat scroll 0 0 #ffffff;
																			border-color: #555555;
																			border-style: solid;
																			border-width: 1px;
																			color: #BBBBBB;">
			</td>
		</tr>
		<tr>
			<td align="center" style="padding:10px"><input type="submit" value="Iscriviti"></td>
		</tr>
		<tr>
			<td align="center">&nbsp;</td>
		</tr>
		<tr>
			<td align="center">
				<div class="icons" style="position:relative;float:left;margin-left:60px;">Seguici anche su facebook<a target="_blank" href="http://it-it.facebook.com/ProBikeRoma" class="facebooklink"></a></div>
			</td>
		</tr>
		</table>
	</form>
 </div>
</div>