<?php $_tplvar = $this->getVars();

// _dump($_tplvar['contenuto']);
// _dump($_tplvar['data']);
// exit();
?>

<div class="ui-grid-a">

<?php if(!empty($_REQUEST['detail_img']) && $_REQUEST['detail_img'] == 'vbn'):?>
	<?php $image = $this->getImageFromVbn($_tplvar['contenuto']['vbn']);?>
	<div style="width:100%;">
		<img src="<?php echo $image?>" alt="" width="100%" style="max-width:800px"/>
	</div>
<?php elseif(!empty($_REQUEST['detail_img']) && $_REQUEST['detail_img'] == 'giacenza'):?>
	<?php foreach ($_tplvar['data'] as $key => $value):?>
	<?php $obj_image = $this->dbGetImageFromBarCode($value['bar_code']);?>
	<?php $product_image = $this->dbGetImageProductFromBarCode($value['bar_code']);?>
	<?php if(!empty($obj_image)):?>
		<?php $image = $obj_image[0]['www_path'].$obj_image[0]['name'];?>
	<?php elseif(!empty($product_image)):?>
		<?php $image = $product_image;?>
	<?php else:?>
	<?php $image = null;?>
	<?php endif;?>
	<div style="width:100%;">
		<img src="<?php echo $image?>" alt="" width="100%" style="max-width:800px"/>
	</div>
	<?php endforeach;?>
<?php else:?>
	<?php foreach ($_tplvar['data'] as $key => $value):?>	
		<table cellpadding="10">
		<tr>
			<td>
				<?php $image = $this->getImageFromVbn($_tplvar['contenuto']['vbn']);?>
	
				<?php if(!empty($image)):?>
					<a href="<?php echo $_tplvar['WWW_ROOT']?>?act=AjaxDetailGiacenza&touch=1&id=<?php echo $_REQUEST['id']?>&detail_img=vbn">
						<img  src="<?php echo $image?>" alt="" width="150" height="150" style="border:1px solid #bbb" />
					</a>
				<?php else:?>
					<img  src="<?php echo $_tplvar['WWW_ROOT'].$_tplvar['IMG_DIR']?>/image.gif" alt="" width="150" height="150" />
				<?php endif;?>	
			</td>
			<td>
				<?php $obj_image = $this->dbGetImageFromBarCode($value['bar_code']);?>
				<?php $product_image = $this->dbGetImageProductFromBarCode($value['bar_code']);?>
				<?php if(!empty($obj_image)):?>
					<?php $image = $obj_image[0]['www_path'].$obj_image[0]['name'];?>
				<?php elseif(!empty($product_image)):?>
					<?php $image = $product_image;?>
				<?php else:?>
				<?php $image = null;?>
				<?php endif;?>
	
				<?php if(!empty($image)):?>
					<a href="<?php echo $_tplvar['WWW_ROOT']?>?act=AjaxDetailGiacenza&touch=1&id=<?php echo $_REQUEST['id']?>&detail_img=giacenza">
						<img  src="<?php echo $image?>" alt="" width="150" height="150" />
					</a>
				<?php else:?>
					<img  src="<?php echo $_tplvar['WWW_ROOT'].$_tplvar['IMG_DIR']?>/image.gif" alt="" width="150" height="150" />
				<?php endif;?>	
			</td>
		</tr>
		<tr>
			<td>Codice VBN</td>
			<td><?php echo $_tplvar['contenuto']['vbn'];?></td>
		</tr>
		<tr>
			<td>Codice Partita</td>
			<td><?php echo $value['bar_code'];?></td>
		</tr>
		<tr>
			<td>Variet&aacute;</td>
			<td><?php echo $_tplvar['contenuto']['nome_it'];?></td>
		</tr>
		<tr>
			<td>Colore</td>
			<td><?php echo $_tplvar['contenuto']['C3'];?> <?php echo $_tplvar['tipo_colore']?></td>
		</tr>
		<tr>
			<td>Altezza</td>
			<td><?php echo $_tplvar['contenuto']['C4'];?></td>
		</tr>
		<tr>
			<td>Quantit&aacute; Imballo</td>
			<td><?php echo $value['quantita'];?></td>
		</tr>
		<tr>
			<td>Disponibilit&aacute;</td>
			<td><?php echo $value['disponibilita'];?></td>
		</tr>
		<tr>
			<td>Prezzo</td>
			<td><?php echo $_tplvar['contenuto'][$_tplvar['key_prezzo']];?></td>
		</tr>
		<tr>
			<td>Provenienza</td>
			<td><?php echo $_tplvar['contenuto']['C5'];?></td>
		</tr>
		<tr>
			<td>Aggiungi al carrello</td>
			<td>
				<?php if(!empty($value) && $value['disponibilita'] > 0):?>
				<?php
				$add_to_basket_url = $_tplvar['WWW_ROOT'].'ShoppingCart';
				if(!empty($_tplvar['contenuto']['id_famiglia']))
				{
					$famiglia = $this->getFamigliById($_tplvar['contenuto']['id_famiglia']);
					$add_to_basket_url .= '/'.$famiglia['famiglia'];
				}
				else
					$add_to_basket_url .= '/-';
				
				if(!empty($_tplvar['contenuto']['nome_it']))
					$add_to_basket_url .= '/'.str_replace("'",'',str_replace('"','',str_replace('%','',str_replace('(','',$_tplvar['contenuto']['nome_it']))));
				else
					$add_to_basket_url .= '-';
				
				$add_to_basket_url .= '/'.$_tplvar['contenuto']['id'].'-'.$_tplvar['contenuto']['id'].'.html';
				?>		
							
				<a href="<?php echo $add_to_basket_url?>" data-role="button" data-icon="plus" data-mini="true" data-iconpos="notext" data-transition="flip">Aggiungi al Carrello</a>
				<?php endif;?>			
			</td>
		</tr>
		</table>
	<?php endforeach;?>
<?php endif;?>
	
</div>
