<?php $_tplvar = $this->getVars();?>

						<select id="nation<?php echo $assign['suffix']?>" name="nation<?php echo $assign['suffix']?>">
							<option <?php if($_tplvar['user_data']['nation'] == 'Albania'):?>selected="selected"<?php endif;?> value="Albania">Albania</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Algeria'):?>selected="selected"<?php endif;?> value="Algeria">Algeria</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Andorra'):?>selected="selected"<?php endif;?> value="Andorra">Andorra</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Angola'):?>selected="selected"<?php endif;?> value="Angola">Angola</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Anguilla'):?>selected="selected"<?php endif;?> value="Anguilla">Anguilla</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Antigua &amp; Barbuda'):?>selected="selected"<?php endif;?> value="Antigua &amp; Barbuda">Antigua &amp; Barbuda</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Argentina'):?>selected="selected"<?php endif;?> value="Argentina">Argentina</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Armenia'):?>selected="selected"<?php endif;?> value="Armenia">Armenia</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Aruba'):?>selected="selected"<?php endif;?> value="Aruba">Aruba</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Australia'):?>selected="selected"<?php endif;?> value="Australia">Australia</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Austria'):?>selected="selected"<?php endif;?> value="Austria">Austria</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Azerbaijan'):?>selected="selected"<?php endif;?> value="Azerbaijan">Azerbaijan</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Azores'):?>selected="selected"<?php endif;?> value="Azores">Azores</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Bahamas'):?>selected="selected"<?php endif;?> value="Bahamas">Bahamas</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Bahrain'):?>selected="selected"<?php endif;?> value="Bahrain">Bahrain</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Barbados'):?>selected="selected"<?php endif;?> value="Barbados">Barbados</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Belarus'):?>selected="selected"<?php endif;?> value="Belarus">Belarus</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Belgium'):?>selected="selected"<?php endif;?> value="Belgium">Belgium</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Belize'):?>selected="selected"<?php endif;?> value="Belize">Belize</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Benin'):?>selected="selected"<?php endif;?> value="Benin">Benin</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Bermuda'):?>selected="selected"<?php endif;?> value="Bermuda">Bermuda</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Bhutan'):?>selected="selected"<?php endif;?> value="Bhutan">Bhutan</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Bolivia'):?>selected="selected"<?php endif;?> value="Bolivia">Bolivia</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Bosnia Herzegovina'):?>selected="selected"<?php endif;?> value="Bosnia Herzegovina">Bosnia Herzegovina</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Botswana'):?>selected="selected"<?php endif;?> value="Botswana">Botswana</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Brazil'):?>selected="selected"<?php endif;?> value="Brazil">Brazil</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Brunei Darussalam'):?>selected="selected"<?php endif;?> value="Brunei Darussalam">Brunei Darussalam</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Bulgaria'):?>selected="selected"<?php endif;?> value="Bulgaria">Bulgaria</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Burkina Faso'):?>selected="selected"<?php endif;?> value="Burkina Faso">Burkina Faso</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Burundi'):?>selected="selected"<?php endif;?> value="Burundi">Burundi</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Cambodia'):?>selected="selected"<?php endif;?> value="Cambodia">Cambodia</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Cameroon'):?>selected="selected"<?php endif;?> value="Cameroon">Cameroon</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Canada'):?>selected="selected"<?php endif;?> value="Canada">Canada</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Cape Verde'):?>selected="selected"<?php endif;?> value="Cape Verde">Cape Verde</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Cayman Islands'):?>selected="selected"<?php endif;?> value="Cayman Islands">Cayman Islands</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'African Republic'):?>selected="selected"<?php endif;?> value="African Republic">Central African Republic</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Chad'):?>selected="selected"<?php endif;?> value="Chad">Chad</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Chile'):?>selected="selected"<?php endif;?> value="Chile">Chile</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'China'):?>selected="selected"<?php endif;?> value="China">China</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Colombia'):?>selected="selected"<?php endif;?> value="Colombia">Colombia</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Comoros'):?>selected="selected"<?php endif;?> value="Comoros">Comoros</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Congo Democratic Republic Of'):?>selected="selected"<?php endif;?> value="Congo Democratic Republic Of">Congo Democratic Republic Of</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Corsica'):?>selected="selected"<?php endif;?> value="Corsica">Corsica</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Costa Rica'):?>selected="selected"<?php endif;?> value="Costa Rica">Costa Rica</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Croatia'):?>selected="selected"<?php endif;?> value="Croatia">Croatia</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Cuba'):?>selected="selected"<?php endif;?> value="Cuba">Cuba</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Cyprus'):?>selected="selected"<?php endif;?> value="Cyprus">Cyprus</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Czech Republic'):?>selected="selected"<?php endif;?> value="Czech Republic">Czech Republic</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Denmark'):?>selected="selected"<?php endif;?> value="Denmark">Denmark</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Djibouti'):?>selected="selected"<?php endif;?> value="Djibouti">Djibouti</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Ecuador'):?>selected="selected"<?php endif;?> value="Ecuador">Ecuador</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Egypt'):?>selected="selected"<?php endif;?> value="Egypt">Egypt</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'El Salvador'):?>selected="selected"<?php endif;?> value="El Salvador">El Salvador</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Eritrea'):?>selected="selected"<?php endif;?> value="Eritrea">Eritrea</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Estonia'):?>selected="selected"<?php endif;?> value="Estonia">Estonia</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Falkland Islands'):?>selected="selected"<?php endif;?> value="Falkland Islands">Falkland Islands</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Faroe Islands'):?>selected="selected"<?php endif;?> value="Faroe Islands">Faroe Islands</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Fiji'):?>selected="selected"<?php endif;?> value="Fiji">Fiji</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Finland'):?>selected="selected"<?php endif;?> value="Finland">Finland</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'France'):?>selected="selected"<?php endif;?> value="France">France</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'French Guiana'):?>selected="selected"<?php endif;?> value="French Guiana">French Guiana</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'French Polynesia'):?>selected="selected"<?php endif;?> value="French Polynesia">French Polynesia</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Gabon'):?>selected="selected"<?php endif;?> value="Gabon">Gabon</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Gambia'):?>selected="selected"<?php endif;?> value="Gambia">Gambia</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Georgia'):?>selected="selected"<?php endif;?> value="Georgia">Georgia</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Germany'):?>selected="selected"<?php endif;?> value="Germany">Germany</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Ghana'):?>selected="selected"<?php endif;?> value="Ghana">Ghana</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Gibraltar'):?>selected="selected"<?php endif;?> value="Gibraltar">Gibraltar</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Greece'):?>selected="selected"<?php endif;?> value="Greece">Greece</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Greenland'):?>selected="selected"<?php endif;?> value="Greenland">Greenland</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Grenada'):?>selected="selected"<?php endif;?> value="Grenada">Grenada</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Guadeloupe'):?>selected="selected"<?php endif;?> value="Guadeloupe">Guadeloupe</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Guam'):?>selected="selected"<?php endif;?> value="Guam">Guam</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Guatemala'):?>selected="selected"<?php endif;?> value="Guatemala">Guatemala</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Guinea'):?>selected="selected"<?php endif;?> value="Guinea">Guinea</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Guinea-Bissau'):?>selected="selected"<?php endif;?> value="Guinea-Bissau">Guinea-Bissau</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Guyana'):?>selected="selected"<?php endif;?> value="Guyana">Guyana</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Haiti'):?>selected="selected"<?php endif;?> value="Haiti">Haiti</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Hong Kong'):?>selected="selected"<?php endif;?> value="Hong Kong">Hong Kong</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Hungary'):?>selected="selected"<?php endif;?> value="Hungary">Hungary</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Iceland'):?>selected="selected"<?php endif;?> value="Iceland">Iceland</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'India'):?>selected="selected"<?php endif;?> value="India">India</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Indonesia'):?>selected="selected"<?php endif;?> value="Indonesia">Indonesia</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Ireland'):?>selected="selected"<?php endif;?> value="Ireland">Ireland</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Israel'):?>selected="selected"<?php endif;?> value="Israel">Israel</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Italy'):?>selected="selected"<?php endif;?> value="Italy" selected="selected">Italy</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Ivory Coast'):?>selected="selected"<?php endif;?> value="Ivory Coast">Ivory Coast</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Jamaica'):?>selected="selected"<?php endif;?> value="Jamaica">Jamaica</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Japan'):?>selected="selected"<?php endif;?> value="Japan">Japan</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Jordan'):?>selected="selected"<?php endif;?> value="Jordan">Jordan</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Kazakhstan'):?>selected="selected"<?php endif;?> value="Kazakhstan">Kazakhstan</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Kenya'):?>selected="selected"<?php endif;?> value="Kenya">Kenya</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Korea- Republic of'):?>selected="selected"<?php endif;?> value="Korea- Republic of">Korea- Republic of</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Kuwait'):?>selected="selected"<?php endif;?> value="Kuwait">Kuwait</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Kyrgyzstan'):?>selected="selected"<?php endif;?> value="Kyrgyzstan">Kyrgyzstan</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Laos'):?>selected="selected"<?php endif;?> value="Laos">Laos</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Latvia'):?>selected="selected"<?php endif;?> value="Latvia">Latvia</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Lesotho'):?>selected="selected"<?php endif;?> value="Lesotho">Lesotho</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Liechtenstein'):?>selected="selected"<?php endif;?> value="Liechtenstein">Liechtenstein</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Lithuania'):?>selected="selected"<?php endif;?> value="Lithuania">Lithuania</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Luxembourg'):?>selected="selected"<?php endif;?> value="Luxembourg">Luxembourg</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Macau'):?>selected="selected"<?php endif;?> value="Macau">Macau</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Macedonia'):?>selected="selected"<?php endif;?> value="Macedonia">Macedonia</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Madagascar'):?>selected="selected"<?php endif;?> value="Madagascar">Madagascar</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Madeira'):?>selected="selected"<?php endif;?> value="Madeira">Madeira</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Malaysia'):?>selected="selected"<?php endif;?> value="Malaysia">Malaysia</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Maldives'):?>selected="selected"<?php endif;?> value="Maldives">Maldives</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Mali'):?>selected="selected"<?php endif;?> value="Mali">Mali</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Malta'):?>selected="selected"<?php endif;?> value="Malta">Malta</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Marshall Islands'):?>selected="selected"<?php endif;?> value="Marshall Islands">Marshall Islands</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Martinique'):?>selected="selected"<?php endif;?> value="Martinique">Martinique</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Mauritania'):?>selected="selected"<?php endif;?> value="Mauritania">Mauritania</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Mauritius'):?>selected="selected"<?php endif;?> value="Mauritius">Mauritius</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Mexico'):?>selected="selected"<?php endif;?> value="Mexico">Mexico</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Moldova'):?>selected="selected"<?php endif;?> value="Moldova">Moldova</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Monaco'):?>selected="selected"<?php endif;?> value="Monaco">Monaco</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Mongolia'):?>selected="selected"<?php endif;?> value="Mongolia">Mongolia</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Montenegro'):?>selected="selected"<?php endif;?> value="Montenegro">Montenegro</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Montserrat'):?>selected="selected"<?php endif;?> value="Montserrat">Montserrat</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Morocco'):?>selected="selected"<?php endif;?> value="Morocco">Morocco</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Namibia'):?>selected="selected"<?php endif;?> value="Namibia">Namibia</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Nepal'):?>selected="selected"<?php endif;?> value="Nepal">Nepal</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Netherlands'):?>selected="selected"<?php endif;?> value="Netherlands">Netherlands</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'New Caledonia'):?>selected="selected"<?php endif;?> value="New Caledonia">New Caledonia</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'New Zealand'):?>selected="selected"<?php endif;?> value="New Zealand">New Zealand</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'New Zealand Island Territories'):?>selected="selected"<?php endif;?> value="New Zealand Island Territories">New Zealand Island Territories</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Niger'):?>selected="selected"<?php endif;?> value="Niger">Niger</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Nigeria'):?>selected="selected"<?php endif;?> value="Nigeria">Nigeria</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Norway'):?>selected="selected"<?php endif;?> value="Norway">Norway</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Oman'):?>selected="selected"<?php endif;?> value="Oman">Oman</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Pakistan'):?>selected="selected"<?php endif;?> value="Pakistan">Pakistan</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Panama'):?>selected="selected"<?php endif;?> value="Panama">Panama</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Paraguay'):?>selected="selected"<?php endif;?> value="Paraguay">Paraguay</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Peru'):?>selected="selected"<?php endif;?> value="Peru">Peru</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Philippines'):?>selected="selected"<?php endif;?> value="Philippines">Philippines</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Poland'):?>selected="selected"<?php endif;?> value="Poland">Poland</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Portugal'):?>selected="selected"<?php endif;?> value="Portugal">Portugal</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Puerto Rico'):?>selected="selected"<?php endif;?> value="Puerto Rico">Puerto Rico</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Qatar'):?>selected="selected"<?php endif;?> value="Qatar">Qatar</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Reunion'):?>selected="selected"<?php endif;?> value="Reunion">Reunion</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Romania'):?>selected="selected"<?php endif;?> value="Romania">Romania</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Russia'):?>selected="selected"<?php endif;?> value="Russia">Russia</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Samoa'):?>selected="selected"<?php endif;?> value="Samoa">Samoa</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'San Marino'):?>selected="selected"<?php endif;?> value="San Marino">San Marino</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Sao Tome &amp; Principe'):?>selected="selected"<?php endif;?> value="Sao Tome &amp; Principe">Sao Tome &amp; Principe</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Sardinia'):?>selected="selected"<?php endif;?> value="Sardinia">Sardinia</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Saudi Arabia'):?>selected="selected"<?php endif;?> value="Saudi Arabia">Saudi Arabia</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Senegal'):?>selected="selected"<?php endif;?> value="Senegal">Senegal</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Serbia'):?>selected="selected"<?php endif;?> value="Serbia">Serbia</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Seychelles'):?>selected="selected"<?php endif;?> value="Seychelles">Seychelles</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Sicily'):?>selected="selected"<?php endif;?> value="Sicily">Sicily</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Sierra Leone'):?>selected="selected"<?php endif;?> value="Sierra Leone">Sierra Leone</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Singapore'):?>selected="selected"<?php endif;?> value="Singapore">Singapore</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Slovak Republic'):?>selected="selected"<?php endif;?> value="Slovak Republic">Slovak Republic</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Slovenia'):?>selected="selected"<?php endif;?> value="Slovenia">Slovenia</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Solomon Islands'):?>selected="selected"<?php endif;?> value="Solomon Islands">Solomon Islands</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Somalia'):?>selected="selected"<?php endif;?> value="Somalia">Somalia</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'South Africa'):?>selected="selected"<?php endif;?> value="South Africa">South Africa</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Spain'):?>selected="selected"<?php endif;?> value="Spain">Spain</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Spain – Balearic Islands'):?>selected="selected"<?php endif;?> value="Spain – Balearic Islands">Spain – Balearic Islands</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Spain – Canary Islands'):?>selected="selected"<?php endif;?> value="Spain – Canary Islands">Spain – Canary Islands</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Spanish North African Territories'):?>selected="selected"<?php endif;?> value="Spanish North African Territories">Spanish North African Territories</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Spitzbergen'):?>selected="selected"<?php endif;?> value="Spitzbergen">Spitzbergen</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Sri Lanka'):?>selected="selected"<?php endif;?> value="Sri Lanka">Sri Lanka</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'St Christopher (St Kitts) &amp; Nevis'):?>selected="selected"<?php endif;?> value="St Christopher (St Kitts) &amp; Nevis">St Christopher (St Kitts) &amp; Nevis</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'St Helena'):?>selected="selected"<?php endif;?> value="St Helena">St Helena</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'St Lucia'):?>selected="selected"<?php endif;?> value="St Lucia">St Lucia</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'St Pierre &amp; Miquelon'):?>selected="selected"<?php endif;?> value="St Pierre &amp; Miquelon">St Pierre &amp; Miquelon</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'St Vincent &amp; The Grenadines'):?>selected="selected"<?php endif;?> value="St Vincent &amp; The Grenadines">St Vincent &amp; The Grenadines</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Suriname'):?>selected="selected"<?php endif;?> value="Suriname">Suriname</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Swaziland'):?>selected="selected"<?php endif;?> value="Swaziland">Swaziland</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Sweden'):?>selected="selected"<?php endif;?> value="Sweden">Sweden</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Switzerland'):?>selected="selected"<?php endif;?> value="Switzerland">Switzerland</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Syria'):?>selected="selected"<?php endif;?> value="Syria">Syria</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Tahiti'):?>selected="selected"<?php endif;?> value="Tahiti">Tahiti</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Taiwan'):?>selected="selected"<?php endif;?> value="Taiwan">Taiwan</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Tajikistan'):?>selected="selected"<?php endif;?> value="Tajikistan">Tajikistan</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Tanzania'):?>selected="selected"<?php endif;?> value="Tanzania">Tanzania</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Thailand'):?>selected="selected"<?php endif;?> value="Thailand">Thailand</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Togo'):?>selected="selected"<?php endif;?> value="Togo">Togo</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Tonga'):?>selected="selected"<?php endif;?> value="Tonga">Tonga</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Trinidad &amp; Tobago'):?>selected="selected"<?php endif;?> value="Trinidad &amp; Tobago">Trinidad &amp; Tobago</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Tunisia'):?>selected="selected"<?php endif;?> value="Tunisia">Tunisia</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Turkey'):?>selected="selected"<?php endif;?> value="Turkey">Turkey</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Turkmenistan'):?>selected="selected"<?php endif;?> value="Turkmenistan">Turkmenistan</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Turks &amp; Caicos Islands'):?>selected="selected"<?php endif;?> value="Turks &amp; Caicos Islands">Turks &amp; Caicos Islands</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Tuvalu'):?>selected="selected"<?php endif;?> value="Tuvalu">Tuvalu</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Uganda'):?>selected="selected"<?php endif;?> value="Uganda">Uganda</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Ukraine'):?>selected="selected"<?php endif;?> value="Ukraine">Ukraine</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'United Arab Emirates'):?>selected="selected"<?php endif;?> value="United Arab Emirates">United Arab Emirates</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'United Kingdom'):?>selected="selected"<?php endif;?> value="United Kingdom">United Kingdom</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'United Kingdom – Channel Islands'):?>selected="selected"<?php endif;?> value="United Kingdom – Channel Islands">United Kingdom – Channel Islands</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'United States Of America'):?>selected="selected"<?php endif;?> value="United States Of America">United States Of America</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Uruguay'):?>selected="selected"<?php endif;?> value="Uruguay">Uruguay</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Uzbekistan'):?>selected="selected"<?php endif;?> value="Uzbekistan">Uzbekistan</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Vanuatu'):?>selected="selected"<?php endif;?> value="Vanuatu">Vanuatu</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Vatican City State'):?>selected="selected"<?php endif;?> value="Vatican City State">Vatican City State</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Venezuela'):?>selected="selected"<?php endif;?> value="Venezuela">Venezuela</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Vietnam'):?>selected="selected"<?php endif;?> value="Vietnam">Vietnam</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Wallis &amp; Futuna Islands'):?>selected="selected"<?php endif;?> value="Wallis &amp; Futuna Islands">Wallis &amp; Futuna Islands</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Western Samoa'):?>selected="selected"<?php endif;?> value="Western Samoa">Western Samoa</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Yemen'):?>selected="selected"<?php endif;?> value="Yemen">Yemen</option>
							<option <?php if($_tplvar['user_data']['nation'] == 'Zambia'):?>selected="selected"<?php endif;?> value="Zambia">Zambia</option>
						</select>