<?php 
$_tplvar = $this->getVars();

$key_search = $assign['key_session'];
$order_by = $assign['order_by'];
$action = $assign['action'];
$field_name = $assign['field_name'];
?>

<?php if($_SESSION[$key_search]['order_type'] == 'ASC'):?>
	<a style="width:140px" data-role="button" <?php if($_SESSION[$key_search]['order_by'] == $order_by):?>data-icon="arrow-d"<?php endif;?> href="<?php echo $_tplvar['WWW_ROOT'];?>?act=<?php echo $action?>&order_by=<?php echo $order_by?>&order_type=DESC" class="order"><?php echo $field_name?></a>
	<?php if($_SESSION[$key_search]['order_by'] == $order_by):?>
	<?php endif;?>
<?php else:?>
	<a style="width:140px" data-role="button" <?php if($_SESSION[$key_search]['order_by'] == $order_by):?>data-icon="arrow-u"<?php endif;?> href="<?php echo $_tplvar['WWW_ROOT'];?>?act=<?php echo $action?>&order_by=<?php echo $order_by?>&order_type=ASC" class="order"><?php echo $field_name?></a>
	<?php if($_SESSION[$key_search]['order_by'] == $order_by):?>
	<?php endif;?>
<?php endif;?>
