<?php $_tplvar = $this->getVars();?>



<script type="text/javascript">
function showConfirmDelete(id)
{
	var el = document.getElementById(id);
	if(el.style.visibility == 'hidden')
		el.style.visibility = 'visible';
	else
		el.style.visibility = 'hidden';
}
</script>

<style>
.tablesorter td {padding: 15px 96px;}
</style>

<!--BOX PER LA RICERCA-->
	<?php 
	$assign['show_combo'] = false;
	$assign['show_calendar'] = false;
	$assign['show_combo_brand'] = false;	
	$assign['show_checkboxes'] = false;
	$assign['show_fornitori'] = false;
	?>
    <?php //echo $this->getPartial('shared/BoxSearch', $assign);?>
<!--BOX PER LA RICERCA-->
<article class="module width_full">
<header><h3 class="tabs_involved">Carrelli Aperti</h3></header>
<div class="tab_container">
			<div id="tab1" class="tab_content">
					<table class="tablesorter" cellspacing="0" cellpadding="0">
					<tr>
						<td width="50">
						<?php
						$assign['key_session'] = 'Charts';
						$assign['order_by'] = 'id';
						$assign['action'] = 'Charts';
						$assign['field_name'] = '#ID';							
						$assign['params'] = $params;
						$this->getPartial('shared/SortField', $assign);
						?>
						</td>
						<td width="150">
						<?php
						$assign['key_session'] = 'Charts';
						$assign['order_by'] = 'data_inserimento_riga';
						$assign['action'] = 'Charts';
						$assign['field_name'] = 'DATA';							
						$assign['params'] = $params;
						$this->getPartial('shared/SortField', $assign);
						?>
						</td>
						<!--<td width="100">
						<?php
//						$assign['key_session'] = 'Charts';
//						$assign['order_by'] = 'importo';
//						$assign['action'] = 'Charts';
//						$assign['field_name'] = 'IMPORTO';							
//						$assign['params'] = $params;
//						$this->getPartial('shared/SortField', $assign);
						?>
						</td>
						--></td>
						<td width="100">CLIENTE</td>
						<td nowrap="nowrap">VAI AL CARRELLO</td>
<!-- 						<td nowrap="nowrap">SPEDISCI ORDINE</td> -->
<!--                        <td width="100">CANCELLA</td>-->
					</tr>
					<script>
					function swapCheckbox(div_id, action, id)
					{
						$.ajax({
							  url: '<?php echo $_tplvar['WWW_ROOT']?>?act=AjaxEcmSetOption',
							  type: 'POST',
							  dataType: 'html',
							  data: 'id='+id+'&action='+action,
							  success: function(html){
								  if($('#'+div_id).css('background-color') == 'rgb(34, 139, 34)')
									  	$('#'+div_id).css('background-color', '#FF0000');
								  else
									  	$('#'+div_id).css('background-color', '#228b22');
								  $('#'+div_id).html(html);								  
							  }
							});	
					}
					</script>
				<?php foreach ($_tplvar['list'] as $key => $value):?>
					<tr>
						<td>
                            #<?php echo $value['id'];?>
						</td>
						<td nowrap="nowrap">
                            <?php
                            	$exp = explode(' ', $value['data_inserimento_riga']);
                            	echo $value['data_inserimento_riga'];
                            ?>
						</td>
						<!--<td><?php echo $this->getFormatPrice(round(str_replace(',', '.', $_tplvar['giacenze']), 2, PHP_ROUND_HALF_UP));?></td>
						--><td nowrap="nowrap">
						<?php echo $value['user']['username']?>
						</td>
                       	<td class="actions" nowrap="nowrap">
							<a class="edit" target="_blank" href="http://shop-oddone.biz/?act=Login&from_admin=1&id=<?php echo $value['user']['id']?>">VAI AL CARRELLO</a>
							<div id="giacenze_<?php echo $value['id'];?>" style="border:1px solid #993300;background: url('<?php echo $_tplvar['WWW_ROOT']?>theme/styles/<?php echo $_tplvar['theme']?>/images/back.png') repeat scroll transparent;background-color:#fff;left:20px;display:none;position:absolute;z-index:1000"></div>
						</td>
						<!--  
						<td class="actions" nowrap="nowrap">
<!--							<a class="delete" href="javascript:void(0);" onclick="javascript:$.fancybox(html_delete_<?php echo $value['id'];?>);">CANCELLA</a>-->
<!--						</td>-->
					</tr>
				<?php endforeach;?>						
				</table>
		</div>
</div>
                <!-- Page Navigation -->
                <?php
                if(!empty($_REQUEST['id_category'])) 
                	$assign['params'] = '&id_category='.$_REQUEST['id_category'];
                ?>
				<?php echo $this->getPartial('shared/Paging', $assign);?>
				<!-- /Page Navigation -->
				
                <!-- Export Excel -->
                <?php $assign['url'] = $_tplvar['WWW_ROOT'].'?act='.$_REQUEST['act'].'&export=1';?>
				<?php echo $this->getPartial('shared/ButtonExcelExport', $assign);?>
				<!-- /Export Excel -->

				