<?php
$_tplvar = $this->getVars();

//_dump($_tplvar);
//exit();
?>
<!doctype html>
<html lang="en">

<head>
	<meta charset="utf-8"/>
	<title>Amministrazione Iaform</title>
	
	<link rel="stylesheet" href="<?php echo $_tplvar['WWW_ROOT']?>css/layout.css" type="text/css" media="screen" />
	<!--[if lt IE 9]>
	<link rel="stylesheet" href="<?php echo $_tplvar['WWW_ROOT']?>css/ie.css" type="text/css" media="screen" />
	<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->

	<?php echo $this->getEncoding();?>
	<?php $this->getSeoMetatag();?>

	<meta name="language" content="<?php echo $_SESSION['lang'];?>">
	<META HTTP-EQUIV="CACHE-CONTROL" CONTENT="NO-CACHE">
	<META HTTP-EQUIV="Pragma" CONTENT="no-cache">
	<META NAME="ROBOTS" CONTENT="NOINDEX,NOFOLLOW">

	<link rel="shortcut icon" href="<?php echo STORE_WWW_ROOT_PATH?>img/web/favico.png" />


	
	<!-- 
	<link rel="stylesheet" id="reset-css" href="<?php echo $_tplvar['WWW_ROOT']?>themes/styles/common-css/reset.css?ver=1.0" type="text/css" media="screen" />
	<link rel="stylesheet" id="text-css" href="<?php echo $_tplvar['WWW_ROOT']?>themes/styles/<?php echo $_tplvar['theme']?>/css/text.css?ver=1.0" type="text/css" media="screen" />
	<link rel="stylesheet" id="grid-960-css" href="<?php echo $_tplvar['WWW_ROOT']?>themes/styles/common-css/960.css?ver=1.0" type="text/css" media="screen" />
	<link rel="stylesheet" id="style-css" href="<?php echo $_tplvar['WWW_ROOT']?>themes/styles/<?php echo $_tplvar['theme']?>/css/style.css?ver=1.0" type="text/css" media="screen" />
	<link rel="stylesheet" href="<?php echo $_tplvar['WWW_ROOT']?>/style/style.css" type="text/css" media="screen" />
 	-->
	<!-- <script  src="<?php echo $_tplvar['WWW_ROOT'].$_tplvar['JS_DIR'];?>/jQuery/jquery-1.3.min.js"></script>-->
	<script type="text/javascript" src="<?php echo $_tplvar['WWW_ROOT'].$_tplvar['JS_DIR'];?>/javascript.js"></script>

	
	<style>
	/* STYLE PER IL FOCUS DELLE TEXT */
	.focus {
	    border: 2px solid #C0C0C0;
	}
	/* STYLE PER IL FOCUS DELLE TEXT */

	/* STYLE PER IL LIGHTBOX */
	.black_overlay{
		display: none;
		position: absolute;
		top: 0%;
		left: 0%;
		width: 100%;
		height: 2000px;
		background-color: black;
		z-index:1001;
		-moz-opacity: 0.8;
		opacity:.80;
		filter: alpha(opacity=80);
	}
	.white_content {
		z-index:1002;
	}
	/* STYLE PER IL LIGHTBOX */
	</style>
	
	<script src="<?php echo $_tplvar['WWW_ROOT']?>javascript/jquery-1.5.2.min.js" type="text/javascript"></script>
	<script src="<?php echo $_tplvar['WWW_ROOT']?>javascript/hideshow.js" type="text/javascript"></script>
	<script src="<?php echo $_tplvar['WWW_ROOT']?>javascript/jquery.tablesorter.min.js" type="text/javascript"></script>
	<script type="text/javascript" src="<?php echo $_tplvar['WWW_ROOT']?>javascript/jquery.equalHeight.js"></script>
	

	
	
	
	<!-- FANCY APPS -->
	<script type="text/javascript" src="<?php echo $_tplvar['WWW_ROOT'].$_tplvar['JS_DIR'];?>/fancyapps-fancyBox/lib/jquery-1.7.2.min.js"></script>
	<script type="text/javascript" src="<?php echo $_tplvar['WWW_ROOT'].$_tplvar['JS_DIR'];?>/fancyapps-fancyBox/lib/jquery.mousewheel-3.0.6.pack.js"></script>
	<script type="text/javascript" src="<?php echo $_tplvar['WWW_ROOT'].$_tplvar['JS_DIR'];?>/fancyapps-fancyBox/source/jquery.fancybox.js?v=2.0.6"></script>
	<link rel="stylesheet" type="text/css" href="<?php echo $_tplvar['WWW_ROOT'].$_tplvar['JS_DIR'];?>/fancyapps-fancyBox/source/jquery.fancybox.css?v=2.0.6" media="screen" />
	<link rel="stylesheet" type="text/css" href="<?php echo $_tplvar['WWW_ROOT'].$_tplvar['JS_DIR'];?>/fancyapps-fancyBox/source/helpers/jquery.fancybox-buttons.css?v=1.0.2" />
	<script type="text/javascript" src="<?php echo $_tplvar['WWW_ROOT'].$_tplvar['JS_DIR'];?>/fancyapps-fancyBox/source/helpers/jquery.fancybox-buttons.js?v=1.0.2"></script>
	<link rel="stylesheet" type="text/css" href="<?php echo $_tplvar['WWW_ROOT'].$_tplvar['JS_DIR'];?>/fancyapps-fancyBox/source/helpers/jquery.fancybox-thumbs.css?v=1.0.2" />
	<script type="text/javascript" src="<?php echo $_tplvar['WWW_ROOT'].$_tplvar['JS_DIR'];?>/fancyapps-fancyBox/source/helpers/jquery.fancybox-thumbs.js?v=1.0.2"></script>
	<script type="text/javascript" src="<?php echo $_tplvar['WWW_ROOT'].$_tplvar['JS_DIR'];?>/fancyapps-fancyBox/source/helpers/jquery.fancybox-media.js?v=1.0.0"></script>
	<script>jQuery.noConflict();</script>
	<!-- FANCY APPS -->
<!-- 
<script type="text/javascript" src="http://code.jquery.com/jquery-latest.min.js"></script>
<script type="text/javascript" src="<?php echo $_tplvar['WWW_ROOT']?>javascript/fancybox/lib/jquery.mousewheel-3.0.6.pack.js"></script>
<link rel="stylesheet" href="<?php echo $_tplvar['WWW_ROOT']?>javascript/fancybox/source/jquery.fancybox.css?v=2.1.5" type="text/css" media="screen" />
<script type="text/javascript" src="<?php echo $_tplvar['WWW_ROOT']?>javascript/fancybox/source/jquery.fancybox.pack.js?v=2.1.5"></script>
<link rel="stylesheet" href="<?php echo $_tplvar['WWW_ROOT']?>javascript/fancybox/source/helpers/jquery.fancybox-buttons.css?v=1.0.5" type="text/css" media="screen" />
<script type="text/javascript" src="<?php echo $_tplvar['WWW_ROOT']?>javascript/fancybox/source/helpers/jquery.fancybox-buttons.js?v=1.0.5"></script>
<script type="text/javascript" src="<?php echo $_tplvar['WWW_ROOT']?>javascript/fancybox/source/helpers/jquery.fancybox-media.js?v=1.0.6"></script>
<link rel="stylesheet" href="<?php echo $_tplvar['WWW_ROOT']?>javascript//fancybox/source/helpers/jquery.fancybox-thumbs.css?v=1.0.7" type="text/css" media="screen" />
<script type="text/javascript" src="<?php echo $_tplvar['WWW_ROOT']?>javascript/fancybox/source/helpers/jquery.fancybox-thumbs.js?v=1.0.7"></script>
 -->
	
	<script type="text/javascript">
	jQuery.noConflict();
	jQuery(document).ready(function() 
   	{ 
		//jQuery(".tablesorter").tablesorter(); 
	});
  	 
	jQuery(document).ready(function() {

	//When page loads...
	jQuery(".tab_content").hide(); //Hide all content
	jQuery("ul.tabs li:first").addClass("active").show(); //Activate first tab
	jQuery(".tab_content:first").show(); //Show first tab content

	//On Click Event
	jQuery("ul.tabs li").click(function() {

		jQuery("ul.tabs li").removeClass("active"); //Remove any "active" class
		jQuery(this).addClass("active"); //Add "active" class to selected tab
		jQuery(".tab_content").hide(); //Hide all tab content

		var activeTab = jQuery(this).find("a").attr("href"); //Find the href attribute value to identify the active tab + content
		jQuery(activeTab).fadeIn(); //Fade in the active ID content
		return false;
	});

});
    </script>
    <script type="text/javascript">
    jQuery(function(){
        //jQuery('.column').equalHeight();
    });
	</script>
</head>
<html>
<body>

<div id="fade" class="black_overlay">
	<img src="<?php echo $_tplvar['WWW_ROOT'].$_tplvar['IMG_DIR']?>/loading.gif" width="30" style="top: 25%;left: 50%;position:absolute;">
</div>

	<header id="header">
		<hgroup>
			<h1 class="site_title" style="font-size:18px"><?php echo PREFIX_META_TITLE?></h1>
		</hgroup>
			<?php echo $this->getPartial('shared/MenuTop');?>
		
	</header> <!-- end of header bar -->
	

	<section id="main" class="column">

		<?php $this->getPartial($_tplvar['tpl_action']);?>

		<div class="spacer"></div>
		<!--FOOTER-->
		<?php $this->getPartial('Footer');?>
	    <!-- / FOOTER-->		
	</section>
	
</body>
	<script>
	jQuery('input[type="text"]').focus(function() {
	    jQuery(this).addClass("focus");
	});
	 
	jQuery('input[type="text"]').blur(function() {
	    jQuery(this).removeClass("focus");
	});	
	</script>
</html>