<?php $_tplvar = $this->getVars();?>

<script type="text/javascript">
<!--
function sendFilter(obj)
{
	var id = obj.options[obj.selectedIndex].value;
	document.location.href = '<?php echo $_tplvar['WWW_ROOT']?>?act=<?php echo $_tplvar['action_class_name']?>&id_size_type='+id;
}
//-->
</script>
	<article class="module width_full" style="width:100%">

		<header><h3 class="tabs_involved">Lista Fornitori</h3></header>

		<div class="tab_container">
			<div id="tab1" class="tab_content">
					<table class="tablesorter" cellspacing="0">     
					<tr>
						<td colspan="6">
							<table width="100%">
							<tr>
								<td>
								<?php
								$assign['key_session'] = $_tplvar['action_class_name'];
								$assign['order_by'] = 'codice_fornitore';
								$assign['action'] = $_tplvar['action_class_name'];
								$assign['field_name'] = 'CODICE FORNITORE';							
								$this->getPartial('shared/SortField', $assign);
								?>
								</td>
								<td>
								<?php
								$assign['key_session'] = $_tplvar['action_class_name'];
								$assign['order_by'] = 'nome';
								$assign['action'] = $_tplvar['action_class_name'];
								$assign['field_name'] = 'NOMINATIVO';							
								$this->getPartial('shared/SortField', $assign);
								?>
								</td>
								<td>
								<?php
								$assign['key_session'] = $_tplvar['action_class_name'];
								$assign['order_by'] = 'telefono';
								$assign['action'] = $_tplvar['action_class_name'];
								$assign['field_name'] = 'TELEFONO';							
								$this->getPartial('shared/SortField', $assign);
								?>
								</td>
								<td>
								<?php
								$assign['key_session'] = $_tplvar['action_class_name'];
								$assign['order_by'] = 'email';
								$assign['action'] = $_tplvar['action_class_name'];
								$assign['field_name'] = 'EMAIL';							
								$this->getPartial('shared/SortField', $assign);
								?>
								</td>
								<td width="100">MODIFICA</td>
								<td width="100">CANCELLA</td>
							</tr>
							<?php foreach ($_tplvar['list'] as $key => $value):?>
							<tr>
								<td width="120"><?php echo $value['codice_fornitore']?></td>	
								<td width="120"><?php echo $value['nome']?></td>
								<td width="120"><?php echo $value['telefono']?></td>
								<td width="120"><?php echo $value['email']?></td>
								<td width="100"><a href="<?php echo $_tplvar['WWW_ROOT']?>?act=NuovoFornitore&edit=1&id=<?php echo $value['id']?>">MODIFICA</a></td>
								<td width="100"><a href="<?php echo $_tplvar['WWW_ROOT']?>?act=<?php echo $_tplvar['action_class_name']?>&delete=1&id=<?php echo $value['id']?>">CANCELLA</a></td>
							</tr>
							<?php endforeach;?>
							</table>
						</td>
					</tr>	
				</table>
				
                <!-- Page Navigation -->
				<?php echo $this->getPartial('shared/Paging');?>
				<!-- /Page Navigation -->
                
                <!-- Export Excel -->
                <?php $assign['url'] = $_tplvar['WWW_ROOT'].'?act='.$_REQUEST['act'].'&export=1';?>
				<?php echo $this->getPartial('shared/ButtonExcelExport', $assign);?>
				<!-- /Export Excel -->
		</div>
	</div>
</article>