<?php
$_tplvar = $this->getVars();

//_dump($_tplvar);
//exit();
?>
<!doctype html>
<html lang="en">

<head>
	<meta charset="utf-8"/>
	<title><?php echo PREFIX_META_TITLE?></title>
	
	<link rel="stylesheet" href="<?php echo $_tplvar['WWW_ROOT']?>css/layout.css" type="text/css" media="screen" />
	<!--[if lt IE 9]>
	<link rel="stylesheet" href="<?php echo $_tplvar['WWW_ROOT']?>css/ie.css" type="text/css" media="screen" />
	<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->
	<script src="<?php echo $_tplvar['WWW_ROOT']?>javascript/jquery-1.5.2.min.js" type="text/javascript"></script>
	<script src="<?php echo $_tplvar['WWW_ROOT']?>javascript/hideshow.js" type="text/javascript"></script>
	<script src="<?php echo $_tplvar['WWW_ROOT']?>javascript/jquery.tablesorter.min.js" type="text/javascript"></script>
	<script type="text/javascript" src="<?php echo $_tplvar['WWW_ROOT']?>javascript/jquery.equalHeight.js"></script>
	<script type="text/javascript">
	$(document).ready(function() 
    	{ 
      	  $(".tablesorter").tablesorter(); 
   	 } 
	);
	$(document).ready(function() {

	//When page loads...
	$(".tab_content").hide(); //Hide all content
	$("ul.tabs li:first").addClass("active").show(); //Activate first tab
	$(".tab_content:first").show(); //Show first tab content

	//On Click Event
	$("ul.tabs li").click(function() {

		$("ul.tabs li").removeClass("active"); //Remove any "active" class
		$(this).addClass("active"); //Add "active" class to selected tab
		$(".tab_content").hide(); //Hide all tab content

		var activeTab = $(this).find("a").attr("href"); //Find the href attribute value to identify the active tab + content
		$(activeTab).fadeIn(); //Fade in the active ID content
		return false;
	});

});
    </script>
    <script type="text/javascript">
    $(function(){
        $('.column').equalHeight();
    });
</script>

</head>
<body>
	<header id="header">
		<hgroup>
			<h1 class="site_title" style="font-size:18px"><a href="index.php"><?php echo PREFIX_META_TITLE?></a></h1>
		</hgroup>
	</header> <!-- end of header bar -->
	
	<section id="main" class="column">

		<form action="<?php echo $_tplvar['WWW_ROOT']?>?act=Login" method="post">
		
			<article class="module width_full">
				<header><h3>Login Utente</h3></header>
					<div class="module_content">
							<fieldset>
								<label>Username</label>
								<input name="username" type="text" class="fields" id="username" style="width:75%" />
							</fieldset>
							<fieldset>
								<label>Password</label>
								<input name="pwd" type="password" class="fields" id="password" style="width:75%" />
							</fieldset>
							
							<div class="clear"></div>
					</div>
				<footer>
					<div class="submit_link">
						<input type="submit" value="LOGIN" class="alt_btn">
						<input type="submit" value="Reset">
					</div>
				</footer>
			</article>		
					
		</form>
	

		<div class="spacer"></div>
	</section>
</body>
</html>
