<?php 
$_tplvar = $this->getVars();
?>
<?php if($_tplvar['print']):?>
<?php
$_tplvar['BaseBarCodeGenerator']->output();
?>
<script type="text/javascript">
<!--
window.print();
//-->
</script>
<?php else:?>

<form action="<?php echo $_tplvar['WWW_ROOT']?>?act=<?php echo $_tplvar['action_class_name']?>" method="post">
<table>
<tr>
	<td>INSERISCI IL CODICE DA GENERARE</td>
	<td><input type="text" name="code"></td>
</tr>
<tr>
	<td colspan="2"><input type="submit" name="search" value="GENERA" /></td>
</tr>
</table>
</form>
<?php endif;?>
