<div id="page-content" class="clearfix">
			
			<h1>Cerca il file o la parola sul DataBase</h1>
			
			<h2>Ricerca sul &quot;Data Base&quot;</h2>
	    <div class="inner-box clearfix">
			
			  
                
         
         
                
			


  <div id="form-block-big">

<div class="contenitore">
<label for="field_1">Filtro di Ricerca</label>
<select name="quantita"  id="quantita" class="short">
   <option>Cerca su tutto</option>
  <option>Cerca per Cliente</option>
  <option>Cerca per Magazzino</option>
  <option>Cerca per Reso</option>
  <option>Cerca per Vendita</option>
</select>
<br />
<label for="field_1">Ricerca per parola chiave</label>
<input type="text" value="Lorem" name="txtField1" id="field_1" class="short" />



<div>
<input type="button" class="submit" value="CERCA" />

</div>
<br />
<br />
<br />
<div id="table-block" style="margin:auto;">
<table cellspacing="0" cellpadding="0" align="left">
    <tbody>
        <tr class="header">
            <td>Rsultato della ricerca</td>

        </tr>
        <tr>

            <td class="actions"><a class="edit" href="#">mply dummy text of the printing and typesetting industry. <span style="color:#090;">Lorem</span> Ipsum has</a></td>
           
        </tr>
        
        <tr class="alternate">
        
            <td class="actions"><a class="edit" href="#">mply dummy text of the printing and typesetting industry. <span style="color:#090;">Lorem</span> Ipsum has</a></td>
         
        </tr>
        
       
     
    </tbody>
</table>
				
                <!-- Page Navigation -->
				<ul class="paginator">
					<li><a href="#">Previous</a></li>
					<li class="current"><a href="#">1</a></li>
					<li><a href="#">2</a></li>
					<li><a href="#">3</a></li>
					<li><a href="#">4</a></li>
					<li><a href="#">5</a></li>
					<li><a href="#">Next</a></li>
				</ul>
				<!-- /Page Navigation -->
                
                
				</div>

</div>

</div>





</div>

</div>