<?php $_tplvar = $this->getVars();?>

					<table cellspacing="10" cellpadding="0">
						<tr>
							<?php
							foreach ($_tplvar['header_list'] as $key => $value)
							{
								foreach ($value as $k => $val)
								{
									if($key == 0 && $k != 'id' && $k != 'id_type')
									{
										?><td width="100"><?php 
										$KEY_TO_DISPLAY[] = $k;
										$assign['key_session'] = $_tplvar['action_class_name'];
										$assign['order_by'] = $k;
										$assign['action'] = $_tplvar['action_class_name'];
										$assign['field_name'] = strtoupper($k);							
										$this->getPartial('shared/SortField', $assign);
										?></td><?php 
									}
								}
							}
							?>
							
                           <td width="100">MODIFICA</td>
                           <td width="100">CANCELLA</td>
						</tr>
					<?php foreach ($_tplvar['list'] as $value):?>
					<tr>
						<?php foreach ($KEY_TO_DISPLAY as $to_display):?>
						<td><?php echo $value[$to_display]?>&nbsp;</td>
						<?php endforeach;?>
						<td><a href="<?php echo $_tplvar['WWW_ROOT']?>?act=SetupNewSizeType&edit=1&id=<?php echo $value['id']?>">MODIFICA</a></td>
						<td><a href="<?php echo $_tplvar['WWW_ROOT']?>?act=SetupSizeType&delete=1&id=<?php echo $value['id']?>">CANCELLA</a></td>
					</tr>
					<?php endforeach;?>
				</table>
				
                <!-- Page Navigation -->
                <?php
                if(!empty($_REQUEST['order_by'])) 
                	$assign['params'] = '&order_by='.$_REQUEST['order_by'];
                if(!empty($_REQUEST['order_type'])) 
                	$assign['params'] .= '&order_type='.$_REQUEST['order_type'];
                if(!empty($_REQUEST['pageID'])) 
                	$assign['params'] .= '&pageID='.$_REQUEST['pageID'];
                	?>
				<?php echo $this->getPartial('shared/Paging', $assign);?>
				<!-- /Page Navigation -->
                
                <!-- Export Excel -->
                <?php //$assign['url'] = $_tplvar['WWW_ROOT'].'?act='.$_REQUEST['act'].'&export=1';?>
				<?php //echo $this->getPartial('shared/ButtonExcelExport', $assign);?>
				<!-- /Export Excel -->
				