<?php $_tplvar = $this->getVars();?>
<form action="<?php echo $_tplvar['WWW_ROOT']?>?act=<?php echo $_tplvar['action_class_name']?>" method="post">
<?php if(!empty($_tplvar['data']['id']))?>
	<input type="hidden" name="id" value="<?php echo $_tplvar['data']['id']?>">
<br><br>
	Tipo Taglia <input type="text" name="type" value="<?php echo $_tplvar['data']['type']?>">
	
<br><br>
	<input type="submit" name="save" value="Salva">
	<input type="reset" class="submit" name="cancel" value="Cancella">
</form>
